const cardData = [
    {idx: 0, code: "KickOff", name: "킥오프21", otherNames: ["킥오프", "베이스"], image: "https://indvel.github.io/fcmsquad/resources/cards/KickOff21.png", type: "fm", color: "white"},
    {idx: 1, code: "KR02", name: "2002한국 아이콘", otherNames: ["일반"], image: "https://indvel.github.io/fcmsquad/resources/cards/2002KR_ICON.png", type: "fm", color: "white"},
    {idx: 2, code: "PI", name: "프라임 아이콘", otherNames: ["프아"], image: "https://indvel.github.io/fcmsquad/resources/cards/PrimeIcon.png", type: "fm", color: "black"},
    {idx: 3, code: "TD21", name: "탑 더비 아이콘", otherNames: ["탑더비"], image: "https://indvel.github.io/fcmsquad/resources/cards/TopDirby.png", type: "fm", color: "white"},
    {idx: 4, code: "KH12", name: "KH12", otherNames: ["KH"], image: "https://indvel.github.io/fcmsquad/resources/cards/KH12.png", type: "fm", color: "white"},
    {idx: 5, code: "KH02", name: "KH02", otherNames: ["KH", "월드투어", "WT"], image: "https://indvel.github.io/fcmsquad/resources/cards/KH02.png", type: "fm", color: "black"},
    {idx: 6, code: "KFA21", name: "KFA21", otherNames: ["KFA", "한국"], image: "https://indvel.github.io/fcmsquad/resources/cards/KH12.png", type: "fm", color: "white"},
    {idx: 7, code: "FD21", name: "Fantastic Duo 21", otherNames: ["판타스틱 듀오", "판듀21", "판듀"], image: "https://indvel.github.io/fcmsquad/resources/cards/FantasticDuo21.png", type: "fm", color: "white"},
    {idx: 8, code: "WT21", name: "WT21 아이콘", otherNames: ["월드투어", "WT"], image: "https://indvel.github.io/fcmsquad/resources/cards/WT21.png", type: "fm", color: "white"},
    {idx: 9, code: "CMA21", name: "첼시 엠버서더 아이콘", otherNames: ["첼앰", "첼엠", "CMA", "첼시"], image: "https://indvel.github.io/fcmsquad/resources/cards/ChelseaAmb.png", type: "fm", color: "white"},
    {idx: 10, code: "TOE21", name: "Top Of Europe 21 아이콘", otherNames: ["TOE", "TOE21", "유럽"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOE21_Icons.png", type: "fm", color: "white"},
    {idx: 11, code: "PB", name: "프리미엄 베이스", otherNames: ["프베", "베이스", "프리미엄"], image: "https://indvel.github.io/fcmsquad/resources/cards/PremiumBase.png", type: "fm", color: "white"},
    {idx: 12, code: "NI", name: "내셔널 아이콘", otherNames: ["내셔널", "NI", "내아"], image: "https://indvel.github.io/fcmsquad/resources/cards/NationalIcon.png", type: "fm", color: "white"},
    {idx: 13, code: "FutMas21", name: "풋마스21 아이콘", otherNames: ["풋마스", "FUTMAS"], image: "https://indvel.github.io/fcmsquad/resources/cards/Futmas21.png", type: "fm", color: "white"},
    {idx: 14, code: "RE02", name: "Remember 2002", otherNames: ["2002", "리멤버2002", "리멤버", "RE02", "똥그리", "땡그리", "동그리", "동그랑땡"], image: "https://indvel.github.io/fcmsquad/resources/cards/Remember02.png", type: "fm", color: "white"},
    {idx: 15, code: "RE02", name: "Remember 2002_Others", otherNames: ["리멤버", "RE02", "똥그리", "땡그리", "동그리", "동그랑땡"], image: "https://indvel.github.io/fcmsquad/resources/cards/Remember02_Others.png", type: "fm", color: "white"},
    {idx: 16, code: "UCL22", name: "UCL22 그룹스테이지", otherNames: ["챔스22", "22챔스", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/No-Card.png", type: "fm", color: "white"},
    {idx: 17, code: "UCL22", name: "UCL22 16강", otherNames: ["챔스22", "22챔스", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL22_16.png", type: "fm", color: "white"},
    {idx: 18, code: "UCL22", name: "UCL22 8강", otherNames: ["챔스22", "22챔스", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL22_8.png", type: "fm", color: "white"},
    {idx: 19, code: "UCL22", name: "UCL22 4강", otherNames: ["챔스22", "22챔스", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL22_4.png", type: "fm", color: "white"},
    {idx: 20, code: "UCL22", name: "UCL22 파이널", otherNames: ["챔스22", "22챔스", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL22_Final.png", type: "fm", color: "white"},
    {idx: 21, code: "UCL22_STAR", name: "UCL22 Best", otherNames: ["22챔베", "챔베22", "챔베", "챔스", "별", "별카드", "챔스22"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL22_Best.png", type: "fm", color: "white"},
    {idx: 22, code: "TOTS22_LIVE", name: "TOTS22", otherNames: ["토츠22", "22토츠", "토츠"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTS22.png", type: "fm", color: "white"},
    {idx: 23, code: "TOTS22_UT", name: "UTOTS22", otherNames: ["얼토츠22", "22얼토츠", "얼토츠", "토츠", "별", "별카드", "별토츠"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTS22_UT.png", type: "fm", color: "#FFFFAA"},
    {idx: 24, code: "TOTY22", name: "TOTY22 Nominee", otherNames: ["22토티", "토티22", "노미니", "토티"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTY22_Nominee.png", type: "fm", color: "white"},
    {idx: 25, code: "TOTY22", name: "TOTY22 HM", otherNames: ["22파토", "파토22", "HM", "토티", "아너블멘션"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTY22_HM.png", type: "fm", color: "white"},
    {idx: 26, code: "TOTY22", name: "TOTY22 NYI", otherNames: ["22토티", "토티22", "토티"], image: "https://indvel.github.io/fcmsquad/resources/cards/NYI_Icon.png", type: "fm", color: "white"},
    {idx: 27, code: "TOTY22_Final", name: "TOTY22 Final", otherNames: ["22파토", "파토22", "파토", "토티", "파이널", "별", "별카드", "별토티"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTY22_Final.png", type: "fm", color: "#D3F0FC"},
    {idx: 28, code: "LEGACY22", name: "LEGACY22", otherNames: ["22레거시", "레거시22", "레거시"], image: "https://indvel.github.io/fcmsquad/resources/cards/Legacy22.png", type: "fm", color: "white"},
    {idx: 29, code: "FS22", name: "FutureStars22", otherNames: ["퓨처스타", "퓨처", "퓨스"], image: "https://indvel.github.io/fcmsquad/resources/cards/No-Card.png", type: "fm", color: "white"},
    {idx: 30, code: "HERO22", name: "Hero22", otherNames: ["히어로22", "22히어로", "히어로"], image: "https://indvel.github.io/fcmsquad/resources/cards/Hero22.png", type: "fm", color: "white"},
    {idx: 31, code: "FB22", name: "FlashBack22", otherNames: ["플래시백", "플백"], image: "https://indvel.github.io/fcmsquad/resources/cards/FlashBack22.png", type: "fm", color: "white"},
    {idx: 32, code: "NOS", name: "NOS22", otherNames: ["노스22", "22노스", "노스"], image: "https://indvel.github.io/fcmsquad/resources/cards/NOS22.png", type: "fm", color: "white"},
    {idx: 33, code: "ISS", name: "ISS22_2", otherNames: ["ISS"], image: "https://indvel.github.io/fcmsquad/resources/cards/IconSuperStar_2.png", type: "fm", color: "white"},
    {idx: 34, code: "RS22", name: "레트로 썸머 22", otherNames: ["RS", "썸머", "레썸", "써머"], image: "https://indvel.github.io/fcmsquad/resources/cards/RS22.png", type: "fm", color: "white"},
    {idx: 35, code: "RS22_ICON", name: "레트로 썸머 22 아이콘", otherNames: ["RS", "썸머", "레썸", "써머"], image: "https://indvel.github.io/fcmsquad/resources/cards/RS22_Icon.png", type: "fm", color: "white"},
    {idx: 36, code: "NUMBER", name: "LN22 아이콘_7번", otherNames: ["LN22", "LN", "레전더리 넘버", "레넘", "엘엔"], image: "https://indvel.github.io/fcmsquad/resources/cards/LegendaryNumbers22_7.png", type: "fm", color: "white"},
    {idx: 37, code: "RM22", name: "레알 엠버서더", otherNames: ["레엠", "RMA"], image: "https://indvel.github.io/fcmsquad/resources/cards/RMA22.png", type: "fm", color: "#664B00"},
    {idx: 38, code: "RM22", name: "레알 엠버서더 아이콘", otherNames: ["레엠", "RMA"], image: "https://indvel.github.io/fcmsquad/resources/cards/RMA22_Icons.png", type: "fm", color: "#664B00"},
    {idx: 39, code: "KOT", name: "TT22", otherNames: ["TT22", "22TT", "TT", "티티", "녹즙"], image: "https://indvel.github.io/fcmsquad/resources/cards/TopTransfers22.png", type: "fm", color: "white"},
    {idx: 40, code: "TT22_ICON", name: "TT22 아이콘", otherNames: ["TT22", "22TT", "TT", "티티", "녹즙"], image: "https://indvel.github.io/fcmsquad/resources/cards/TT22_Icon.png", type: "fm", color: "white"},
    {idx: 41, code: "NOS", name: "NOS22 STAR", otherNames: ["노스22", "22노스", "노스", "노스별", "별카드"], image: "https://indvel.github.io/fcmsquad/resources/cards/NOS22_STAR.png", type: "fm", color: "white"},
    {idx: 42, code: "FS22", name: "FutureStar22", otherNames: ["퓨처스타", "퓨처", "스타", "퓨스"], image: "https://indvel.github.io/fcmsquad/resources/cards/FutureStar22.png", type: "fm", color: "white"},
    {idx: 43, code: "FB22", name: "FlashBack22_2", otherNames: ["플래시백", "플래시백22", "플백"], image: "https://indvel.github.io/fcmsquad/resources/cards/FlashBack22_2.png", type: "fm", color: "white"},
    {idx: 44, code: "FB_Icon", name: "FlashBack22 아이콘", otherNames: ["플래시백", "플백", "아이콘"], image: "https://indvel.github.io/fcmsquad/resources/cards/FlashBack22_Icon.png", type: "fm", color: "white"},
    {idx: 45, code: "LN22", name: "LN22 아이콘_1번", otherNames: ["LN22", "LN", "레전더리 넘버", "레넘", "엘엔"], image: "https://indvel.github.io/fcmsquad/resources/cards/LegendaryNumbers22_1.png", type: "fm", color: "white"},
    {idx: 46, code: "LN22", name: "LN22 아이콘_4번", otherNames: ["LN22", "LN", "레전더리 넘버", "레넘", "엘엔"], image: "https://indvel.github.io/fcmsquad/resources/cards/LegendaryNumbers22_4.png", type: "fm", color: "white"},
    {idx: 47, code: "LN22", name: "LN22 아이콘_5번", otherNames: ["LN22", "LN", "레전더리 넘버", "레넘", "엘엔"], image: "https://indvel.github.io/fcmsquad/resources/cards/LegendaryNumbers22_5.png", type: "fm", color: "white"},
    {idx: 48, code: "ISS2", name: "ISS22_1", otherNames: ["ISS"], image: "https://indvel.github.io/fcmsquad/resources/cards/IconSuperStar_1.png", type: "fm", color: "black"},
    {idx: 49, code: "NG23", name: "NG23", otherNames: ["진재", "NG23", "NG", "엔지", "엔쥐", "뉴젠", "뉴제너레이션", "진화재료", "재료"], image: "https://indvel.github.io/fcmsquad/resources/cards/NewGeneration23.png", type: "fm", color: "white"},
    {idx: 50, code: "WC22_BASE", name: "월드컵22 베이스(11.17출시)", otherNames: ["월드컵", "월베", "베이스"], image: "https://indvel.github.io/fcmsquad/resources/cards/WorldCup22_Base.png", type: "fm", color: "white"},
    {idx: 51, code: "WC", name: "월드컵22 라이징스타", otherNames: ["월드컵", "월스", "월컵", "라이징"], image: "https://indvel.github.io/fcmsquad/resources/cards/WorldCup22_RisingStar.png", type: "fm", color: "white"},
    {idx: 52, code: "WC", name: "월드컵22 베스트", otherNames: ["월드컵", "월베", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WorldCup22_Best.png", type: "fm", color: "white"},
    {idx: 53, code: "WC", name: "월드컵22 헤드라인", otherNames: ["월드컵", "월헤", "중국방석", "헤드라인", "월컵", "방석"], image: "https://indvel.github.io/fcmsquad/resources/cards/WorldCup22_Headlines.png", type: "fm", color: "white"},
    {idx: 54, code: "WC_ICON", name: "월드컵22 아이콘", otherNames: ["월드컵", "월콘", "월드콘", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WCIcon.png", type: "fm", color: "#664B00"},
    {idx: 55, code: "WC", name: "월드컵22 스타_아르헨티나", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_ARGENTINA.png", type: "fm", color: "white"},
    {idx: 56, code: "WC", name: "월드컵22 스타_호주", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_AUSTRALIA.png", type: "fm", color: "white"},
    {idx: 57, code: "WC", name: "월드컵22 스타_벨기에", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_BELGIUM.png", type: "fm", color: "white"},
    {idx: 58, code: "WC", name: "월드컵22 스타_브라질", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_BRAZIL.png", type: "fm", color: "white"},
    {idx: 59, code: "WC", name: "월드컵22 스타_카메룬", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_CAMEROON.png", type: "fm", color: "white"},
    {idx: 60, code: "WC", name: "월드컵22 스타_캐나다", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_CANADA.png", type: "fm", color: "white"},
    {idx: 61, code: "WC", name: "월드컵22 스타_코스타리카", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_COSTARICA.png", type: "fm", color: "white"},
    {idx: 63, code: "WC", name: "월드컵22 스타_크로아티아", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_CROATIA.png", type: "fm", color: "white"},
    {idx: 64, code: "WC", name: "월드컵22 스타_덴마크", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_DENMARK.png", type: "fm", color: "white"},
    {idx: 65, code: "WC", name: "월드컵22 스타_에콰도르", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_ECUADOR.png", type: "fm", color: "white"},
    {idx: 66, code: "WC", name: "월드컵22 스타_잉글랜드", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_ENGLAND.png", type: "fm", color: "white"},
    {idx: 67, code: "WC", name: "월드컵22 스타_프랑스", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_FRANCE.png", type: "fm", color: "white"},
    {idx: 68, code: "WC", name: "월드컵22 스타_독일", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_GERMANY.png", type: "fm", color: "white"},
    {idx: 69, code: "WC", name: "월드컵22 스타_가나", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_GHANA.png", type: "fm", color: "white"},
    {idx: 70, code: "WC", name: "월드컵22 스타_이란", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_IRAN.png", type: "fm", color: "white"},
    {idx: 71, code: "WC", name: "월드컵22 스타_일본", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_JAPAN.png", type: "fm", color: "white"},
    {idx: 72, code: "WC",  name: "월드컵22 스타_대한민국", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_KOREA.png", type: "fm", color: "white"},
    {idx: 73, code: "WC", name: "월드컵22 스타_멕시코", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_MEXICO.png", type: "fm", color: "white"},
    {idx: 74, code: "WC", name: "월드컵22 스타_모로코", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_MOROCCO.png", type: "fm", color: "white"},
    {idx: 75, code: "WC", name: "월드컵22 스타_네덜란드", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_NETHERLANDS.png", type: "fm", color: "white"},
    {idx: 76, code: "WC", name: "월드컵22 스타_폴란드", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_POLAND.png", type: "fm", color: "white"},
    {idx: 77, code: "WC", name: "월드컵22 스타_포르투갈", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_PORTUGAL.png", type: "fm", color: "white"},
    {idx: 78, code: "WC", name: "월드컵22 스타_카타르", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_QATAR.png", type: "fm", color: "white"},
    {idx: 79, code: "WC", name: "월드컵22 스타_사우디아라비아", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_SAUDIARABIA.png", type: "fm", color: "white"},
    {idx: 80, code: "WC", name: "월드컵22 스타_세네갈", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_SENEGAL.png", type: "fm", color: "white"},
    {idx: 81, code: "WC", name: "월드컵22 스타_세르비아", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_SERBIA.png", type: "fm", color: "white"},
    {idx: 82, code: "WC", name: "월드컵22 스타_스페인", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_SPAIN.png", type: "fm", color: "white"},
    {idx: 83, code: "WC", name: "월드컵22 스타_스위스", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_SWITZERLAND.png", type: "fm", color: "white"},
    {idx: 84, code: "WC", name: "월드컵22 스타_튀니지", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_TUNISIA.png", type: "fm", color: "white"},
    {idx: 85, code: "WC", name: "월드컵22 스타_우루과이", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_URUGUAY.png", type: "fm", color: "white"},
    {idx: 86, code: "WC", name: "월드컵22 스타_미국", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_USA.png", type: "fm", color: "white"},
    {idx: 87, code: "WC", name: "월드컵22 스타_웨일스", otherNames: ["월드컵", "월스", "월컵"], image: "https://indvel.github.io/fcmsquad/resources/cards/WC22_WALES.png", type: "fm", color: "white"},
    {idx: 88, code: "Shapeshifter23", name: "IF23", otherNames: ["IF23", "이프23", "이프"], image: "https://indvel.github.io/fcmsquad/resources/cards/IF23.png", type: "fm", color: "white"},
    {idx: 89, code: "ISS", name: "ISS23", otherNames: ["ISS"], image: "https://indvel.github.io/fcmsquad/resources/cards/IconSuperStar_2.png", type: "fm", color: "white"},
    {idx: 90, code: "FL23", name: "Fearless23", otherNames: ["피어리스", "FL"], image: "https://indvel.github.io/fcmsquad/resources/cards/Fearless23.png", type: "fm", color: "white"},
    {idx: 91, code: "FL23_ICON", name: "Fearless23 아이콘", otherNames: ["피어리스", "FL", "아이콘"], image: "https://indvel.github.io/fcmsquad/resources/cards/Fearless23_Icons.png", type: "fm", color: "white"},
    {idx: 92, code: "TOTS23", name: "TOTS23 베이스", otherNames: ["토츠23", "23토츠", "토츠", "베이스"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTS23_Base.png", type: "fm", color: "white"},
    {idx: 93, code: "TOTS23", name: "TOTS23", otherNames: ["토츠23", "23토츠", "토츠"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTS23_Moment.png", type: "fm", color: "white"},
    {idx: 94, code: "TOTS23_UT", name: "UTOTS23", otherNames: ["얼토츠23", "23얼토츠", "얼토츠", "토츠"], image: "https://indvel.github.io/fcmsquad/resources/cards/UTOTS23.png", type: "fm", color: "#242424"},
    {idx: 95, code: "UCL23", name: "UCL23", otherNames: ["챔스23", "23챔스", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL23_TOP25.png", type: "fm", color: "white"},
    {idx: 96, code: "UCL23", name: "UCL23 Tournament", otherNames: ["챔스23", "23챔스", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL23_Tournament.png", type: "fm", color: "white"},
    {idx: 97, code: "UCL23", name: "UCL23 Best", otherNames: ["23챔베", "챔베22", "챔베", "챔스", "챔스23"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL23_Best.png", type: "fm", color: "white"},
    {idx: 98, code: "TOTY23", name: "TOTY23 Nominee", otherNames: ["토티23", "23토티", "노미니", "토티"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTY23_Low.png", type: "fm", color: "white"},
    {idx: 99, code: "TOTY23_ULT", name: "TOTY23 Final", otherNames: ["23파토", "파토23", "파토", "파이널", "토티"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTY23_Final.png", type: "fm", color: "white"},
    {idx: 100, code: "HERO_JOURNEYS", name: "Hero23", otherNames: ["히어로23", "23히어로", "히어로"], image: "https://indvel.github.io/fcmsquad/resources/cards/HERO23_A.png", type: "fm", color: "white"},
    {idx: 101, code: "EI", name: "이터널 아이콘 LV.1", otherNames: ["이터널", "모먼트"], image: "https://indvel.github.io/fcmsquad/resources/cards/EternalIcons_LV1.png", type: "fm", color: "#FFFFAA"},
    {idx: 102, code: "EI", name: "이터널 아이콘 LV.2", otherNames: ["이터널", "모먼트"], image: "https://indvel.github.io/fcmsquad/resources/cards/EternalIcons_LV2.png", type: "fm", color: "#FFFFAA"},
    {idx: 103, code: "EI", name: "이터널 아이콘 LV.3", otherNames: ["이터널", "모먼트"], image: "https://indvel.github.io/fcmsquad/resources/cards/EternalIcons_LV3.png", type: "fm", color: "#FFFFAA"},
    {idx: 104, code: "EI", name: "이터널 아이콘 LV.4", otherNames: ["이터널", "모먼트"], image: "https://indvel.github.io/fcmsquad/resources/cards/EternalIcons_LV4.png", type: "fm", color: "#FFFFAA"},
    {idx: 105, code: "EI", name: "이터널 아이콘 LV.5", otherNames: ["이터널", "모먼트"], image: "https://indvel.github.io/fcmsquad/resources/cards/EternalIcons_LV5.png", type: "fm", color: "black"},
    {idx: 106, code: "TKL23", name: "TKL23", otherNames: ["K리그", "티케이엘", "케이리그"], image: "https://indvel.github.io/fcmsquad/resources/cards/TKL23.png", type: "fm", color: "white"},
    {idx: 107, code: "HOL23", name: "HOL23", otherNames: ["홀23", "HOL23", "홀"], image: "https://indvel.github.io/fcmsquad/resources/cards/HOL23_High.png", type: "fm", color: "white"},
    {idx: 108, code: "HOL23", name: "HOL23 아이콘", otherNames: ["홀23", "HOL23", "홀"], image: "https://indvel.github.io/fcmsquad/resources/cards/HOL23_Icon.png", type: "fm", color: "white"},
    {idx: 109, code: "FD24", name: "Founders24 베이스", otherNames: ["파운더스24", "파운더스", "베이스", "FC24", "파더", "아빠", "녹즙"], image: "https://indvel.github.io/fcmsquad/resources/cards/FC24_Base.png", type: "fc", color: "black"},
    {idx: 110, code: "FD24", name: "Founders24", otherNames: ["파운더스24", "파운더스", "1차", "파더", "아빠", "녹즙"], image: "https://indvel.github.io/fcmsquad/resources/cards/Founders24.png", type: "fm", color: "white"},
    {idx: 111, code: "FD24", name: "Founders24_Low", otherNames: ["파운더스24", "파운더스", "1차", "파더", "아빠", "녹즙"], image: "https://indvel.github.io/fcmsquad/resources/cards/Founders24_Low.png", type: "fm", color: "white"},
    {idx: 112, code: "FD23_ICON", name: "Founders24 아이콘", otherNames: ["파운더스24", "파운더스", "1차", "아이콘", "파더", "아빠", "녹즙"], image: "https://indvel.github.io/fcmsquad/resources/cards/Founders24_icon.png", type: "fm", color: "white"},
    {idx: 113, code: "WF24", name: "Founders24 2차 ", otherNames: ["파운더스24", "파운더스", "2차", "파더", "아빠"], image: "https://indvel.github.io/fcmsquad/resources/cards/Founders24_2.avif", type: "fc", color: "black"},
    {idx: 114, code: "WF24_ICON", name: "Founders24 2차 아이콘", otherNames: ["파운더스24", "파운더스", "2차", "아이콘", "파더", "아빠"], image: "https://indvel.github.io/fcmsquad/resources/cards/Founders24_2_Icon.avif", type: "fc", color: "black"},
    {idx: 115, code: "KickOff", name: "킥오프(23-24)", otherNames: ["킥오프", "베이스"], image: "https://indvel.github.io/fcmsquad/resources/cards/KickOff23.png", type: "fc", color: "white"},
    {idx: 116, code: "RB24", name: "RecordBreaker23", otherNames: ["레코드", "레브", "레코드브레이커"], image: "https://indvel.github.io/fcmsquad/resources/cards/RecordBreaker23.png", type: "fm", color: "white"},
    {idx: 117, code: "RB24", name: "RecordBreaker23_ICON", otherNames: ["레코드", "레브", "레코드브레이커", "아이콘"], image: "https://indvel.github.io/fcmsquad/resources/cards/RecordBreaker23_ICON.png", type: "fm", color: "white"},
    {idx: 118, code: "UCL24_LIVE", name: "UCL24 베이스", otherNames: ["챔스24", "24챔스", "베이스", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL24_Base.avif", type: "fc", color: "white"},
    {idx: 119, code: "UCL24_LIVE", name: "UCL24 스타", otherNames: ["챔스24", "24챔스", "스타", "챔스"], image: "https://indvel.github.io/fcmsquad/resources/cards/UCL24_Star.avif", type: "fc", color: "white"},
    {idx: 120, code: "JUV24", name: "유벤투스24", otherNames: ["유벤24", "유벤투스", "유벤", "유엠", "유앰"], image: "https://indvel.github.io/fcmsquad/resources/cards/JuventusAmb.png", type: "fc", color: "white"},
    {idx: 121, code: "JUV24", name: "유벤투스24 아이콘&히어로", otherNames: ["유벤24", "유벤투스", "유벤", "유엠", "유앰"], image: "https://indvel.github.io/fcmsquad/resources/cards/JuventusAmb_Icon.png", type: "fc", color: "white"},
    {idx: 122, code: "TI24", name: "트로피 아이콘", otherNames: ["트로피", "트아"], image: "https://indvel.github.io/fcmsquad/resources/cards/TrophyIcons.png", type: "fc", color: "#664B00"},
    {idx: 123, code: "KFA23&18", name: "KFA23&18", otherNames: ["KFA23", "KFA18", "KFA", "크파", "케이에프에이"], image: "https://indvel.github.io/fcmsquad/resources/cards/KFA23&18.png", type: "fc", color: "white"},
    {idx: 124, code: "RIVALS24", name: "Rivals24", otherNames: ["라이벌스", "라이벌", "라벌"], image: "https://indvel.github.io/fcmsquad/resources/cards/Rivals_Mixed.png", type: "fc", color: "white"},
    {idx: 125, code: "RIVALS24_ICON", name: "Rivals24 Icon", otherNames: ["라이벌스", "라이벌", "아이콘", "라벌"], image: "https://indvel.github.io/fcmsquad/resources/cards/Rivals24_Icon.png", type: "fc", color: "#664B00"},
    {idx: 126, code: "RK24", name: "RuleBreakers24", otherNames: ["룰브레이커", "룰브"], image: "https://indvel.github.io/fcmsquad/resources/cards/RuleBreakers24.png", type: "fc", color: "white"},
    {idx: 127, code: "RK24_ICON", name: "RuleBreakers24 아이콘", otherNames: ["룰브레이커", "룰브", "아이콘", "별", "별카드"], image: "https://indvel.github.io/fcmsquad/resources/cards/RuleBreakers24_Icon.png", type: "fc", color: "white"},
    {idx: 128, code: "KO3L", name: "삼국24 아이콘", otherNames: ["삼국", "중국", "아이콘"], image: "https://indvel.github.io/fcmsquad/resources/cards/KO3L_Enchance.png", type: "fc", color: "#FFFFAA"},
    {idx: 129, code: "KO3L", name: "삼국24 아이콘2", otherNames: ["삼국", "중국", "아이콘"], image: "https://indvel.github.io/fcmsquad/resources/cards/KO3L_Icon.png", type: "fc", color: "#FFFFAA"},
    {idx: 130, code: "PSG24", name: "PSG24", otherNames: ["생제", "파리", "피에스지", "이강인"], image: "https://indvel.github.io/fcmsquad/resources/cards/Captain24.avif", type: "fc", color: "white"},
    {idx: 131, code: "TOTY24_LIVE", name: "TOTY24 LIVE", otherNames: ["토티24", "24토티", "토티"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTY24_Live.avif", type: "fc", color: "white"},
    {idx: 132, code: "UT24", name: "UTOTY24", otherNames: ["토티24", "24토티", "토티", "얼토티"], image: "https://indvel.github.io/fcmsquad/resources/cards/UTOTY24.avif", type: "fc", color: "#FFFFAA"},
    {idx: 133, code: "TOTY24_ICON", name: "TOTY24 NYI", otherNames: ["토티24", "24토티", "얼토티", "토티", "아이콘"], image: "https://indvel.github.io/fcmsquad/resources/cards/UTOTY24_Icon.avif", type: "fc", color: "#664B00"},
    {idx: 134, code: "TOTY24_HM", name: "TOTY24_HM", otherNames: ["토티24", "24토티", "토티", "HM", "아너블멘션"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTY24_HM.png", type: "fc", color: "white"},
    {idx: 135, code: "TOTY24_LIVE", name: "TOTY24 베이스", otherNames: ["토티24", "24토티", "토티", "베이스"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTY24_Base.png", type: "fc", color: "white"},
    {idx: 136, code: "FD24_3D", name: "Founders24_3D ", otherNames: ["파운더스24", "파운더스", "2차", "파더", "아빠", "3D"], image: "https://indvel.github.io/fcmsquad/resources/cards/Founders24_3D.png", type: "fc", color: "white"},
    {idx: 137, code: "KFA24", name: "KFA24", otherNames: ["KFA24", "KFA", "크파", "케이에프에이"], image: "https://indvel.github.io/fcmsquad/resources/cards/KFA24.png", type: "fc", color: "white"},
    {idx: 138, code: "LEGACY23", name: "LEGACY23", otherNames: ["23레거시", "레거시23", "레거시"], image: "https://indvel.github.io/fcmsquad/resources/cards/Legacy23.png", type: "fm", color: "white"},
    {idx: 139, code: "KOT", name: "TT22 LOW", otherNames: ["TT22", "22TT", "TT", "티티", "녹즙"], image: "https://indvel.github.io/fcmsquad/resources/cards/TT22_Low.png", type: "fm", color: "white"},
    {idx: 140, code: "TI24", name: "트로피 아이콘_Low", otherNames: ["트로피", "트아", "118", "공짜"], image: "https://indvel.github.io/fcmsquad/resources/cards/TrophyIcons_Low.png", type: "fc", color: "#664B00"},
    {idx: 141, code: "HEROES24", name: "Hero24", otherNames: ["히어로24", "히어로", "카툰", "24히어로"], image: "https://indvel.github.io/fcmsquad/resources/cards/Heroes24.png", type: "fc", color: "white"},
    {idx: 143, code: "HEROES24", name: "Hero24_CARTOON", otherNames: ["히어로24", "히어로", "카툰", "24히어로", "챔스", "UCL"], image: "https://indvel.github.io/fcmsquad/resources/cards/Heroes24_UCL.png", type: "fc", color: "white"},
    {idx: 144, code: "HEROES24", name: "UnsungHero24", otherNames: ["히어로24", "히어로", "카툰", "언성", "UH", "언성히어로", "24히어로"], image: "https://indvel.github.io/fcmsquad/resources/cards/Heroes24_Unsung.png", type: "fc", color: "white"},
    {idx: 145, code: "HT24", name: "HatTrick24", otherNames: ["해트트릭", "해트", "트릭", "신태용", "만우절", "멕시코"], image: "https://indvel.github.io/fcmsquad/resources/cards/DOD24.png", type: "fc", color: "white"},
    {idx: 146, code: "HT24_ICON", name: "HatTrick24_ICON", otherNames: ["해트트릭", "해트", "트릭", "신태용", "만우절", "멕시코", "아이콘"], image: "https://indvel.github.io/fcmsquad/resources/cards/DOD24_ICON.png", type: "fc", color: "#664B00"},
    {idx: 147, code: "CT24", name: "CENTURIONS24", otherNames: ["센츄리온", "센츄", "CT", "센추리온", "센추리얼", "센츄리온스", "센추리온스"], image: "https://indvel.github.io/fcmsquad/resources/cards/CENTURIONS24.png", type: "fc", color: "white"},
    {idx: 148, code: "CT24_ICON", name: "CENTURIONS24_ICON", otherNames: ["센츄리온", "센츄", "CT", "센추리온", "센추리얼", "센츄리온스", "센추리온스"], image: "https://indvel.github.io/fcmsquad/resources/cards/CENTURIONS24_ICON.png", type: "fc", color: "#513D03"},
    {idx: 149, code: "CT24_STAR", name: "CENTURIONS24_STAR", otherNames: ["센츄리온", "센츄", "CT", "센추리온", "센추리얼", "센츄리온스", "센추리온스", "별", "센추별", "별센추", "센츄별", "별센츄", "별카드"], image: "https://indvel.github.io/fcmsquad/resources/cards/CENTURIONS24_STAR.png", type: "fc", color: "white"},
    {idx: 150, code: "KL24", name: "KL24", otherNames: ["KL", "케이엘", "케이리그", "케이", "TKL", "팀케이엘"], image: "https://indvel.github.io/fcmsquad/resources/cards/KL24_LIVE.png", type: "fc", color: "white"},
    {idx: 151, code: "KL24_ICON", name: "KL24_ICON", otherNames: ["KL", "케이엘", "케이리그", "케이", "TKL", "팀케이엘"], image: "https://indvel.github.io/fcmsquad/resources/cards/KL24_ICON.png", type: "fc", color: "#513D03"},
    {idx: 152, code: "TOTS24", name: "TOTS24_BASE", otherNames: ["TOTS", "토츠", "토츠24", "24토츠", "베이스"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTS24_BASE.png", type: "fc", color: "#FCEB8E"},
    {idx: 153, code: "TOTS24", name: "TOTS24_LIVE", otherNames: ["TOTS", "토츠", "토츠24", "24토츠", "라이브"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTS24_ELITE.png", type: "fc", color: "#FCEB8E"},
    {idx: 154, code: "TOTS24_ICON", name: "TOTS24_ICON", otherNames: ["TOTS", "토츠24", "24토츠", "토츠", "아이콘"], image: "https://indvel.github.io/fcmsquad/resources/cards/TOTS24_UTOTS_ICON.png", type: "fc", color: "#513D03"}
];