const playerData = {
	"ucl25": [
		{
			"pid": 234378,
			"className": "[UCL25]",
			"playerKor": "데클런 라이스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p234378_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTFBASE_3.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "CM",
			"ovr": 131,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 247635,
			"className": "[UCL25]",
			"playerKor": "크바라츠헬리아",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p247635_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 73,
			"team": "파리 생제르맹 FC",
			"position": "LW",
			"ovr": 128,
			"nationality": 20,
			"nation": "조지아"
		},
		{
			"pid": 233419,
			"className": "[UCL25]",
			"playerKor": "하피냐",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p233419_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "LM",
			"ovr": 128,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 188545,
			"className": "[UCL25]",
			"playerKor": "R. 레반도프스키",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p188545_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "ST",
			"ovr": 128,
			"nationality": 37,
			"nation": "폴란드"
		},
		{
			"pid": 231443,
			"className": "[UCL25]",
			"playerKor": "우스만 뎀벨레",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p231443.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 73,
			"team": "파리 생제르맹 FC",
			"position": "ST",
			"ovr": 127,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 237383,
			"className": "[UCL25]",
			"playerKor": "A. 바스토니",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p237383_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "CB",
			"ovr": 127,
			"nationality": 27,
			"nation": "이탈리아"
		},
		{
			"pid": 224232,
			"className": "[UCL25]",
			"playerKor": "니콜로 바렐라",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p224232_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "CM",
			"ovr": 127,
			"nationality": 27,
			"nation": "이탈리아"
		},
		{
			"pid": 228093,
			"className": "[UCL25]",
			"playerKor": "마르쿠스 튀람",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p228093_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "ST",
			"ovr": 127,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 243715,
			"className": "[UCL25]",
			"playerKor": "윌리암 살리바",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p243715_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "CB",
			"ovr": 127,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 230621,
			"className": "[UCL25]",
			"playerKor": "G. 돈나룸마",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p230621.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 73,
			"team": "파리 생제르맹 FC",
			"position": "GK",
			"ovr": 126,
			"nationality": 27,
			"nation": "이탈리아"
		},
		{
			"pid": 272834,
			"className": "[UCL25]",
			"playerKor": "주앙 네베스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p272834_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 73,
			"team": "파리 생제르맹 FC",
			"position": "CM",
			"ovr": 126,
			"nationality": 38,
			"nation": "포르투갈"
		},
		{
			"pid": 255253,
			"className": "[UCL25]",
			"playerKor": "비토르 페헤이라",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p255253.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 73,
			"team": "파리 생제르맹 FC",
			"position": "CM",
			"ovr": 126,
			"nationality": 38,
			"nation": "포르투갈"
		},
		{
			"pid": 198176,
			"className": "[UCL25]",
			"playerKor": "스테판 더브레이",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p198176_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "CB",
			"ovr": 126,
			"nationality": 34,
			"nation": "네덜란드"
		},
		{
			"pid": 208128,
			"className": "[UCL25]",
			"playerKor": "하칸 찰하놀루",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p208128.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "CM",
			"ovr": 126,
			"nationality": 48,
			"nation": "튀르키예"
		},
		{
			"pid": 231478,
			"className": "[UCL25]",
			"playerKor": "L. 마르티네스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p231478.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "ST",
			"ovr": 126,
			"nationality": 52,
			"nation": "아르헨티나"
		},
		{
			"pid": 251854,
			"className": "[UCL25]",
			"playerKor": "페드리",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p251854_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "CM",
			"ovr": 126,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 277643,
			"className": "[UCL25]",
			"playerKor": "라민 야말",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p277643_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "RM",
			"ovr": 126,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 264240,
			"className": "[UCL25]",
			"playerKor": "가비",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p264240_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "CM",
			"ovr": 126,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 222665,
			"className": "[UCL25]",
			"playerKor": "M. 외데고르",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p222665.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "CM",
			"ovr": 126,
			"nationality": 36,
			"nation": "노르웨이"
		},
		{
			"pid": 271807,
			"className": "[UCL25]",
			"playerKor": "E. 은와네리",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p271807_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "RW",
			"ovr": 126,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 177683,
			"className": "[UCL25]",
			"playerKor": "얀 조머",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p177683.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "GK",
			"ovr": 125,
			"nationality": 47,
			"nation": "스위스"
		},
		{
			"pid": 226851,
			"className": "[UCL25]",
			"playerKor": "뱅자맹 파바르",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p226851_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "CB",
			"ovr": 125,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 226268,
			"className": "[UCL25]",
			"playerKor": "F. 디마르코",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p226268.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "LWB",
			"ovr": 125,
			"nationality": 27,
			"nation": "이탈리아"
		},
		{
			"pid": 233096,
			"className": "[UCL25]",
			"playerKor": "덴젤 둠프리스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p233096_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "RWB",
			"ovr": 125,
			"nationality": 34,
			"nation": "네덜란드"
		},
		{
			"pid": 210406,
			"className": "[UCL25]",
			"playerKor": "P. 지엘린스키",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p210406_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 131682,
			"team": "롬바르디아 FC",
			"position": "CM",
			"ovr": 125,
			"nationality": 37,
			"nation": "폴란드"
		},
		{
			"pid": 186153,
			"className": "[UCL25]",
			"playerKor": "W. 슈체스니",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p186153_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "GK",
			"ovr": 125,
			"nationality": 37,
			"nation": "폴란드"
		},
		{
			"pid": 263578,
			"className": "[UCL25]",
			"playerKor": "알렉스 발데",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p263578_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "LB",
			"ovr": 125,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 278046,
			"className": "[UCL25]",
			"playerKor": "파우 쿠바르시",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p278046.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "CB",
			"ovr": 125,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 253163,
			"className": "[UCL25]",
			"playerKor": "R. 아라우호",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p253163_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "CB",
			"ovr": 125,
			"nationality": 60,
			"nation": "우루과이"
		},
		{
			"pid": 241486,
			"className": "[UCL25]",
			"playerKor": "쥘 쿤데",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p241486.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "RB",
			"ovr": 125,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 215441,
			"className": "[UCL25]",
			"playerKor": "세루 기라시",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p215441_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "ST",
			"ovr": 125,
			"nationality": 118,
			"nation": "기니"
		},
		{
			"pid": 228702,
			"className": "[UCL25]",
			"playerKor": "프렝키 더용",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p228702.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "CM",
			"ovr": 125,
			"nationality": 34,
			"nation": "네덜란드"
		},
		{
			"pid": 247819,
			"className": "[UCL25]",
			"playerKor": "다비드 라야",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p220901.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "GK",
			"ovr": 125,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 257711,
			"className": "[UCL25]",
			"playerKor": "R. 칼라피오리",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p257711_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "LB",
			"ovr": 125,
			"nationality": 27,
			"nation": "이탈리아"
		},
		{
			"pid": 232580,
			"className": "[UCL25]",
			"playerKor": "가브리에우",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p232580_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "CB",
			"ovr": 125,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 251805,
			"className": "[UCL25]",
			"playerKor": "J. 팀버르",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p251805.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "RB",
			"ovr": 125,
			"nationality": 34,
			"nation": "네덜란드"
		},
		{
			"pid": 251566,
			"className": "[UCL25]",
			"playerKor": "가브리엘 마르치넬리",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p251566_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "LW",
			"ovr": 125,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 205498,
			"className": "[UCL25]",
			"playerKor": "조르지뉴",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p205498.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "CDM",
			"ovr": 125,
			"nationality": 27,
			"nation": "이탈리아"
		},
		{
			"pid": 202811,
			"className": "[UCL25]",
			"playerKor": "E. 마르티네스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p202811_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "GK",
			"ovr": 125,
			"nationality": 52,
			"nation": "아르헨티나"
		},
		{
			"pid": 260247,
			"className": "[UCL25]",
			"playerKor": "M. 로저스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p260247_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "CAM",
			"ovr": 125,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 221697,
			"className": "[UCL25]",
			"playerKor": "올리 왓킨스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p221697_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "ST",
			"ovr": 125,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 252371,
			"className": "[UCL25]",
			"playerKor": "J. 벨링엄",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p252371_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "CAM",
			"ovr": 125,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 238794,
			"className": "[UCL25]",
			"playerKor": "비니시우스 주니어",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p238794_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "LW",
			"ovr": 125,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 212622,
			"className": "[UCL25]",
			"playerKor": "요주아 키미히",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p212622.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "CDM",
			"ovr": 124,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 256790,
			"className": "[UCL25]",
			"playerKor": "J. 무시알라",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p256790_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "CAM",
			"ovr": 124,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 247827,
			"className": "[UCL25]",
			"playerKor": "마이클 올리스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p247827_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "RM",
			"ovr": 124,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 266032,
			"className": "[UCL25]",
			"playerKor": "J. 바이노-기튼스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p266032_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "LM",
			"ovr": 124,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 212194,
			"className": "[UCL25]",
			"playerKor": "율리안 브란트",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p212194_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "CAM",
			"ovr": 124,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 216393,
			"className": "[UCL25]",
			"playerKor": "유리 틸레만스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p216393_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "CM",
			"ovr": 124,
			"nationality": 7,
			"nation": "벨기에"
		},
		{
			"pid": 220834,
			"className": "[UCL25]",
			"playerKor": "마르코 아센시오",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p220834_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "RW",
			"ovr": 124,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 239053,
			"className": "[UCL25]",
			"playerKor": "F. 발베르데",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p239053_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "RB",
			"ovr": 124,
			"nationality": 60,
			"nation": "우루과이"
		},
		{
			"pid": 243812,
			"className": "[UCL25]",
			"playerKor": "호드리구",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p243812_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "RW",
			"ovr": 124,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 231747,
			"className": "[UCL25]",
			"playerKor": "킬리안 음바페",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p231747_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "ST",
			"ovr": 124,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 167495,
			"className": "[UCL25]",
			"playerKor": "마누엘 노이어",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p167495.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "GK",
			"ovr": 123,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 225375,
			"className": "[UCL25]",
			"playerKor": "콘라트 라이머",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p225375.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "RB",
			"ovr": 123,
			"nationality": 4,
			"nation": "오스트리아"
		},
		{
			"pid": 229558,
			"className": "[UCL25]",
			"playerKor": "D. 우파메카노",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p229558_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "CB",
			"ovr": 123,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 209658,
			"className": "[UCL25]",
			"playerKor": "레온 고레츠카",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p209658.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "CDM",
			"ovr": 123,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 213345,
			"className": "[UCL25]",
			"playerKor": "킹슬레 코망",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p213345_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "LM",
			"ovr": 123,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 235073,
			"className": "[UCL25]",
			"playerKor": "그레고르 코벨",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p235073.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "GK",
			"ovr": 123,
			"nationality": 47,
			"nation": "스위스"
		},
		{
			"pid": 229891,
			"className": "[UCL25]",
			"playerKor": "J. 리에르손",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p229891.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "RB",
			"ovr": 123,
			"nationality": 36,
			"nation": "노르웨이"
		},
		{
			"pid": 208333,
			"className": "[UCL25]",
			"playerKor": "엠레 잔",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p208333.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "CB",
			"ovr": 123,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 259716,
			"className": "[UCL25]",
			"playerKor": "D. 스벤손",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p259716_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "LB",
			"ovr": 123,
			"nationality": 46,
			"nation": "스웨덴"
		},
		{
			"pid": 190765,
			"className": "[UCL25]",
			"playerKor": "파스칼 그로스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p190765_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "CDM",
			"ovr": 123,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 204923,
			"className": "[UCL25]",
			"playerKor": "마르셀 자비처",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p204923.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "CDM",
			"ovr": 123,
			"nationality": 4,
			"nation": "오스트리아"
		},
		{
			"pid": 251852,
			"className": "[UCL25]",
			"playerKor": "K. 아데예미",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p251852_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 22,
			"team": "보루시아 도르트문트",
			"position": "RM",
			"ovr": 123,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 229942,
			"className": "[UCL25]",
			"playerKor": "악셀 디사시",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p229942.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "RB",
			"ovr": 123,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 227678,
			"className": "[UCL25]",
			"playerKor": "에즈리 콘사",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p227678_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "CB",
			"ovr": 123,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 212419,
			"className": "[UCL25]",
			"playerKor": "타이론 밍스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p212419.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "CB",
			"ovr": 123,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 200458,
			"className": "[UCL25]",
			"playerKor": "뤼카 디뉴",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p200458.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "LB",
			"ovr": 123,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 236987,
			"className": "[UCL25]",
			"playerKor": "B. 카마라",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p236987.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "CM",
			"ovr": 123,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 231677,
			"className": "[UCL25]",
			"playerKor": "M. 래시포드",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p231677_FCMA_UCLRTF25_ALL_K.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "LW",
			"ovr": 123,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 192119,
			"className": "[UCL25]",
			"playerKor": "티보 쿠르투아",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p192119.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "GK",
			"ovr": 123,
			"nationality": 7,
			"nation": "벨기에"
		},
		{
			"pid": 228618,
			"className": "[UCL25]",
			"playerKor": "페를랑 멘디",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p228618.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "LB",
			"ovr": 123,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 205452,
			"className": "[UCL25]",
			"playerKor": "A. 뤼디거",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p205452.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "CB",
			"ovr": 123,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 197445,
			"className": "[UCL25]",
			"playerKor": "다비드 알라바",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p197445_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "CB",
			"ovr": 123,
			"nationality": 4,
			"nation": "오스트리아"
		},
		{
			"pid": 241637,
			"className": "[UCL25]",
			"playerKor": "A. 추아메니",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p241637_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "CM",
			"ovr": 123,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 177003,
			"className": "[UCL25]",
			"playerKor": "루카 모드리치",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p177003.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "CM",
			"ovr": 123,
			"nationality": 10,
			"nation": "크로아티아"
		},
		{
			"pid": 237086,
			"className": "[UCL25]",
			"playerKor": "김민재",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p237086_FCMK_UCLRTF25_ALL.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/UCL25RTF_LIVE_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "CB",
			"ovr": 122,
			"nationality": 167,
			"nation": "대한민국"
		}
	],
	'utoty25': [
		{
			"pid": 203376,
			"className": "[25UTOTY]",
			"playerKor": "버질 반데이크",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p203376_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 9,
			"team": "리버풀 FC",
			"position": "CB",
			"ovr": 138,
			"nationality": 34,
			"nation": "네덜란드"
		},
		{
			"pid": 209331,
			"className": "[25UTOTY]",
			"playerKor": "모하메드 살라",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p209331_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 9,
			"team": "리버풀 FC",
			"position": "RW",
			"ovr": 138,
			"nationality": 111,
			"nation": "이집트"
		},
		{
			"pid": 238794,
			"className": "[25UTOTY]",
			"playerKor": "비니시우스 주니어",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p238794_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "LW",
			"ovr": 138,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 252371,
			"className": "[25UTOTY]",
			"playerKor": "J. 벨링엄",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p252371_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "CM",
			"ovr": 138,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 243715,
			"className": "[25UTOTY]",
			"playerKor": "윌리암 살리바",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p243715_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 1,
			"team": "아스날 FC",
			"position": "CB",
			"ovr": 138,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 231747,
			"className": "[25UTOTY]",
			"playerKor": "킬리안 음바페",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p231747_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "ST",
			"ovr": 138,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 257534,
			"className": "[25UTOTY]",
			"playerKor": "C. 파머",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p257534_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 5,
			"team": "첼시 FC",
			"position": "CAM",
			"ovr": 138,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 204963,
			"className": "[25UTOTY]",
			"playerKor": "카르바할",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p204963_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "RB",
			"ovr": 138,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 202811,
			"className": "[25UTOTY]",
			"playerKor": "E. 마르티네스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p202811_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 2,
			"team": "아스톤 빌라 FC",
			"position": "GK",
			"ovr": 138,
			"nationality": 52,
			"nation": "아르헨티나"
		},
		{
			"pid": 231866,
			"className": "[25UTOTY]",
			"playerKor": "로드리",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p231866_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 10,
			"team": "맨체스터 시티 FC",
			"position": "CDM",
			"ovr": 138,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 210035,
			"className": "[25UTOTY]",
			"playerKor": "그리말도",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p210035_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 32,
			"team": "바이어 04 레버쿠젠",
			"position": "LB",
			"ovr": 138,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 200104,
			"className": "[25UTOTY]",
			"playerKor": "손흥민",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p200104_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 18,
			"team": "토트넘 홋스퍼 FC",
			"position": "LM",
			"ovr": 138,
			"nationality": 167,
			"nation": "대한민국"
		},
		{
			"pid": 232656,
			"className": "[25UTOTY]",
			"playerKor": "테오",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p232656_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 131681,
			"team": "밀라노 FC",
			"position": "LB",
			"ovr": 138,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 239053,
			"className": "[25UTOTY]",
			"playerKor": "F. 발베르데",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p239053_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "CM",
			"ovr": 138,
			"nationality": 60,
			"nation": "우루과이"
		},
		{
			"pid": 205452,
			"className": "[25UTOTY]",
			"playerKor": "A. 뤼디거",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p205452_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 243,
			"team": "레알 마드리드 CF",
			"position": "CB",
			"ovr": 138,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 20801,
			"className": "[25UTOTY]",
			"playerKor": "크리스티아누 호날두",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p20801_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 112139,
			"team": "알 나스르 FC",
			"position": "ST",
			"ovr": 138,
			"nationality": 38,
			"nation": "포르투갈"
		},
		{
			"pid": 202126,
			"className": "[25UTOTY]",
			"playerKor": "해리 케인",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p202126_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 21,
			"team": "FC 바이에른 뮌헨",
			"position": "ST",
			"ovr": 138,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 277643,
			"className": "[25UTOTY]",
			"playerKor": "라민 야말",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p277643_FCKJ_UTOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_UTOTY_1.png",
			"teamid": 241,
			"team": "FC 바르셀로나",
			"position": "RW",
			"ovr": 138,
			"nationality": 45,
			"nation": "스페인"
		}
	],
	'toty25icon': [
		{
			"pid": 267897,
			"className": "[25TOTY]",
			"playerKor": "게르트 뮐러",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p267897_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "ST",
			"ovr": 134,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 7826,
			"className": "[25TOTY]",
			"playerKor": "로빈 반페르시",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p7826_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "ST",
			"ovr": 134,
			"nationality": 34,
			"nation": "네덜란드"
		},
		{
			"pid": 255358,
			"className": "[25TOTY]",
			"playerKor": "사뮈엘 에토",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p255358_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "RW",
			"ovr": 134,
			"nationality": 103,
			"nation": "카메룬"
		},
		{
			"pid": 239062,
			"className": "[25TOTY]",
			"playerKor": "A. 네스타",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p239062_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CB",
			"ovr": 134,
			"nationality": 27,
			"nation": "이탈리아"
		},
		{
			"pid": 238438,
			"className": "[25TOTY]",
			"playerKor": "조지 베스트",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p238438_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "RM",
			"ovr": 134,
			"nationality": 35,
			"nation": "북아일랜드"
		},
		{
			"pid": 247555,
			"className": "[25TOTY]",
			"playerKor": "가린샤",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p247555_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "RW",
			"ovr": 134,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 254571,
			"className": "[25TOTY]",
			"playerKor": "리켈메",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p254571_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CAM",
			"ovr": 133,
			"nationality": 52,
			"nation": "아르헨티나"
		},
		{
			"pid": 256339,
			"className": "[25TOTY]",
			"playerKor": "B. 슈바인슈타이거",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p256339_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CM",
			"ovr": 133,
			"nationality": 21,
			"nation": "독일"
		},
		{
			"pid": 242859,
			"className": "[25TOTY]",
			"playerKor": "C. 마켈렐레",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p242859_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CDM",
			"ovr": 133,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 4202,
			"className": "[25TOTY]",
			"playerKor": "젠나로 가투소",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p4202_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CDM",
			"ovr": 133,
			"nationality": 27,
			"nation": "이탈리아"
		},
		{
			"pid": 239522,
			"className": "[25TOTY]",
			"playerKor": "게리 리네커",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p239522_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "ST",
			"ovr": 133,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 248155,
			"className": "[25TOTY]",
			"playerKor": "이언 라이트",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p248155_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "ST",
			"ovr": 133,
			"nationality": 14,
			"nation": "잉글랜드"
		},
		{
			"pid": 261279,
			"className": "[25TOTY]",
			"playerKor": "카시야스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p261279_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "GK",
			"ovr": 133,
			"nationality": 45,
			"nation": "스페인"
		},
		{
			"pid": 239600,
			"className": "[25TOTY]",
			"playerKor": "로이 킨",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p239600_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CM",
			"ovr": 133,
			"nationality": 25,
			"nation": "아일랜드"
		},
		{
			"pid": 7518,
			"className": "[25TOTY]",
			"playerKor": "베론",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p7518_FCKJ_TOTY25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/TOTY25_LIVE_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CM",
			"ovr": 133,
			"nationality": 52,
			"nation": "아르헨티나"
		}
	],
	'baldicon': [
		{
			"pid": 248450,
			"className": "[RS24]",
			"playerKor": "지네딘 지단",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p248450_FMK_RS24_0829.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/FCMK_RS24_ICON_3.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "LM",
			"ovr": 132,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 248450,
			"className": "[CT24]",
			"playerKor": "지네딘 지단",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p248450_CE24_ICON.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/CE24_ICON3.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CAM",
			"ovr": 130,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 139869,
			"className": "[RS24]",
			"playerKor": "W. 스네이더",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p139869_FMK_RS24_0829.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/FCMK_RS24_ICON_3.png",
			"teamid": 115935,
			"team": "HERO",
			"position": "CAM",
			"ovr": 131,
			"nationality": 34,
			"nation": "네덜란드"
		},
		{
			"pid": 5740,
			"className": "[TOTP25]",
			"playerKor": "야프 스탐",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p5740_FCMK_FC25_ICON_1128.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/FCMK_FC_FOOTBALL_ICON_1.png",
			"teamid": 115935,
			"team": "HERO",
			"position": "CB",
			"ovr": 133,
			"nationality": 34,
			"nation": "네덜란드"
		},
		{
			"pid": 251483,
			"className": "[WW25]",
			"playerKor": "뱅상 콤파니",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p251483_FCMK_WW25_LIVE_1219.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/FCMK_WW25_ICON_1.png",
			"teamid": 115935,
			"team": "HERO",
			"position": "CB",
			"ovr": 134,
			"nationality": 7,
			"nation": "벨기에"
		},
		{
			"pid": 251483,
			"className": "[RS24]",
			"playerKor": "뱅상 콤파니",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p251483_FMK_RS24_0829.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/FCMK_RS24_ICON_3.png",
			"teamid": 115935,
			"team": "HERO",
			"position": "CB",
			"ovr": 131,
			"nationality": 7,
			"nation": "벨기에"
		},
		{
			"pid": 251483,
			"className": "[EURO24]",
			"playerKor": "뱅상 콤파니",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p251483_EURO24_FMK_ICON.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/FCMK_EURO24_HERO_PLAYER_BELGIUM_1.png",
			"teamid": 115935,
			"team": "HERO",
			"position": "CB",
			"ovr": 130,
			"nationality": 7,
			"nation": "벨기에"
		},
		{
			"pid": 1040,
			"className": "[BLD24]",
			"playerKor": "호베르투 카를루스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p1040_BLD24_FCMK.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/BLD24_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "LB",
			"ovr": 133,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 1040,
			"className": "[IM24]",
			"playerKor": "호베르투 카를루스",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p1040_IM24.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/IM24_ICON_SHEILD_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "RW",
			"ovr": 131,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 237064,
			"className": "[BLD24]",
			"playerKor": "호나우두",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p237064_BLD24_FCMK.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/BLD24_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "ST",
			"ovr": 134,
			"nationality": 54,
			"nation": "브라질"
		},
		{
			"pid": 237069,
			"className": "[WW25]",
			"playerKor": "티에리 앙리",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p237069_FCMK_WW25_1219.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/FCMK_WW25_ICON_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "LW",
			"ovr": 134,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 237069,
			"className": "[IM24]",
			"playerKor": "티에리 앙리",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p237069_IM24.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/IM24_ICON_SPEAR_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "ST",
			"ovr": 132,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 237069,
			"className": "[ENI24]",
			"playerKor": "티에리 앙리",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p237069_EURO24_FMK_ICON.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/FCMK_EURO24_ICON_PLAYER_FRANCE_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "LW",
			"ovr": 130,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 1419,
			"className": "[FC치킨]",
			"playerKor": "P. 비에이라",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p1419_FMK_AFD25_0327.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/AFD25_ICON_BASE01.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CDM",
			"ovr": 137,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 1419,
			"className": "[IM24]",
			"playerKor": "P. 비에이라",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p1419_IM24.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/IM24_ICON_SHEILD_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CB",
			"ovr": 132,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 1419,
			"className": "[CT24]",
			"playerKor": "P. 비에이라",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p1419_FCK_CT24.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/FCC_CTR24_STAR_1.png",
			"teamid": 112658,
			"team": "ICON",
			"position": "CDM",
			"ovr": 130,
			"nationality": 18,
			"nation": "프랑스"
		},
		{
			"pid": 20289,
			"className": "[FB25]",
			"playerKor": "야야 투레",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p20289_FCK_FB25.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/FCMK_FB25_ICON_1.png",
			"teamid": 115935,
			"team": "HERO",
			"position": "CM",
			"ovr": 135,
			"nationality": 108,
			"nation": "코트디부아르"
		},
		{
			"pid": 20289,
			"className": "[IM24]",
			"playerKor": "야야 투레",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_24/p20289_IM24.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_23/IM24_ICON_SHEILD_1.png",
			"teamid": 115935,
			"team": "HERO",
			"position": "ST",
			"ovr": 132,
			"nationality": 108,
			"nation": "코트디부아르"
		},
		{
			"pid": 16254,
			"className": "[TOTP25]",
			"playerKor": "팀 하워드",
			"pimage": "https://fco.vod.nexoncdn.co.kr/assets/static/players/players_25/p16254_FCMK_FC25_ICON_1128.png",
			"bimage": "https://fco.vod.nexoncdn.co.kr/assets/content/player/Backgrounds_24/FCMK_FC_FOOTBALL_ICON_1.png",
			"teamid": 115935,
			"team": "HERO",
			"position": "GK",
			"ovr": 133,
			"nationality": 95,
			"nation": "미국"
		}
	]
}