const clubsData = {
    "Argentina Primera División (1)": [
        "Racing Club de Avellaneda",
        "Atlético Tucumán",
        "Banfield",
        "Deportivo Riestra",
        "Rosario Central",
        "Gimnasia y Esgrima La Plata",
        "Defensa y Justicia",
        "Central Córdoba",
        "Unión de Santa Fe",
        "Lanús",
        "Independiente",
        "Newell's Old Boys",
        "Argentinos Juniors",
        "Instituto de Córdoba",
        "Belgrano de Córdoba",
        "Boca Juniors",
        "Estudiantes de La Plata",
        "Independiente Rivadavia",
        "San Lorenzo de Almagro",
        "Platense",
        "Barracas Central",
        "Sarmiento",
        "Vélez Sarsfield",
        "Tigre",
        "Godoy Cruz",
        "River Plate",
        "Talleres de Córdoba",
        "Huracán"
    ],
    "Norway Eliteserien (1)": [
        "Sandefjord Fotball",
        "Fredrikstad FK",
        "Sarpsborg 08",
        "KFUM-Kameratene Oslo",
        "Molde FK",
        "Rosenborg BK",
        "Strømsgodset Toppfotball",
        "Odds Ballklubb",
        "Kristiansund BK",
        "FK Haugesund",
        "HamKam Fotball",
        "SK Brann",
        "Tromsø IL",
        "FK Bodø/Glimt",
        "Lillestrøm SK",
        "Viking FK"
    ],
    "Spain Primera División (1)": [
        "Sevilla FC",
        "Villarreal CF",
        "Athletic Club de Bilbao",
        "Real Madrid",
        "RCD Espanyol",
        "Getafe CF",
        "Real Valladolid",
        "RC Celta de Vigo",
        "FC Barcelona",
        "Rayo Vallecano",
        "CD Leganés",
        "Deportivo Alavés",
        "RCD Mallorca",
        "Real Betis Balompié",
        "Valencia CF",
        "UD Las Palmas",
        "Real Sociedad",
        "Girona FC"
    ],
    "Australia A-League (1)": [
        "Western Sydney Wanderers",
        "Central Coast Mariners",
        "Wellington Phoenix",
        "Newcastle Jets",
        "Sydney FC",
        "Melbourne City",
        "Perth Glory",
        "Western United FC",
        "Melbourne Victory",
        "Macarthur FC",
        "Adelaide United",
        "Brisbane Roar",
        "Auckland FC"
    ],
    "USA Major League Soccer (1)": [
        "New York City FC",
        "New York Red Bulls",
        "Seattle Sounders",
        "D.C. United",
        "Houston Dynamo",
        "Nashville SC",
        "Philadelphia Union",
        "Colorado Rapids",
        "Columbus Crew",
        "Charlotte FC",
        "Orlando City SC",
        "Los Angeles Galaxy",
        "Sporting KC",
        "Inter Miami",
        "FC Dallas",
        "Los Angeles FC",
        "Minnesota United FC",
        "Toronto FC",
        "Austin FC",
        "CF Montréal",
        "St. Louis City SC",
        "New England Revolution",
        "Atlanta United FC",
        "Vancouver Whitecaps",
        "FC Cincinnati",
        "Portland Timbers",
        "San Jose Earthquakes",
        "Real Salt Lake"
    ],
    "Germany 2. Bundesliga (2)": [
        "1. FC Kaiserslautern",
        "SpVgg Greuther Fürth",
        "Karlsruher SC",
        "SSV Ulm 1846",
        "1. FC Magdeburg",
        "1. FC Nürnberg",
        "Hannover 96",
        "SC Paderborn 07",
        "SV Darmstadt 98",
        "FC Schalke 04",
        "SV Elversberg",
        "Eintracht Braunschweig",
        "Fortuna Düsseldorf",
        "Hamburger SV",
        "Hertha BSC",
        "Preußen Münster",
        "1. FC Köln",
        "Jahn Regensburg"
    ],
    "Holland Eredivisie (1)": [
        "NAC Breda",
        "FC Utrecht",
        "PEC Zwolle",
        "NEC Nijmegen",
        "Feyenoord",
        "PSV",
        "FC Groningen",
        "AZ",
        "Almere City FC",
        "Willem II",
        "Fortuna Sittard",
        "Go Ahead Eagles",
        "sc Heerenveen",
        "Heracles Almelo",
        "RKC Waalwijk",
        "Sparta Rotterdam",
        "Ajax",
        "FC Twente"
    ],
    "France Ligue 1 (1)": [
        "RC Strasbourg",
        "Paris Saint-Germain",
        "Stade de Reims",
        "Toulouse FC",
        "AS Saint-Étienne",
        "Angers SCO",
        "RC Lens",
        "FC Nantes",
        "Montpellier HSC",
        "Stade Rennais",
        "Le Havre AC",
        "Olympique de Marseille",
        "Stade Brestois 29",
        "OGC Nice",
        "AJ Auxerre",
        "Olympique Lyonnais",
        "LOSC Lille"
    ],
    "France Ligue 2 (2)": [
        "FC Annecy",
        "USL Dunkerque",
        "Amiens SC",
        "AC Ajaccio",
        "Clermont Foot",
        "SC Bastia",
        "En Avant Guingamp",
        "Paris FC",
        "Red Star FC",
        "FC Martigues",
        "ESTAC Troyes",
        "Pau FC",
        "Stade Lavallois MFC",
        "Rodez Aveyron Football",
        "FC Metz",
        "FC Lorient",
        "SM Caen",
        "Grenoble Foot 38"
    ],
    "Turkey Süper Lig (1)": [
        "Trabzonspor",
        "Adana Demirspor",
        "Çaykur Rizespor",
        "Konyaspor",
        "Istanbul Başakşehir FK",
        "Sivasspor",
        "Antalyaspor",
        "Samsunspor",
        "Bodrumspor",
        "Eyüpspor",
        "Göztepe",
        "Hatayspor",
        "Corendon Alanyaspor",
        "Kayserispor",
        "Gaziantep FK",
        "Kasımpaşa",
        "Fenerbahçe",
        "Galatasaray",
        "Beşiktaş"
    ],
    "England Championship (2)": [
        "West Bromwich Albion",
        "Queens Park Rangers",
        "Cardiff City",
        "Middlesbrough",
        "Millwall",
        "Stoke City",
        "Watford",
        "Swansea City",
        "Leeds United",
        "Preston North End",
        "Coventry City",
        "Bristol City",
        "Norwich City",
        "Oxford United",
        "Blackburn Rovers",
        "Sunderland",
        "Sheffield United",
        "Luton Town",
        "Derby County",
        "Portsmouth",
        "Plymouth Argyle",
        "Hull City",
        "Sheffield Wednesday"
    ],
    "England League Two (4)": [
        "Bradford City",
        "Morecambe",
        "Colchester United",
        "Carlisle United",
        "AFC Wimbledon",
        "Cheltenham Town",
        "Tranmere Rovers",
        "Fleetwood Town",
        "Accrington Stanley",
        "Crewe Alexandra",
        "Barrow",
        "Port Vale",
        "Harrogate Town",
        "Chesterfield",
        "Bromley",
        "Newport County",
        "Grimsby Town",
        "Notts County",
        "Swindon Town",
        "Gillingham",
        "Salford City",
        "Doncaster Rovers",
        "Milton Keynes Dons",
        "Walsall"
    ],
    "Spain Segunda División (2)": [
        "Córdoba CF",
        "Real Zaragoza",
        "SD Huesca",
        "Granada CF",
        "Elche CF",
        "Levante UD",
        "CD Tenerife",
        "FC Cartagena",
        "Real Sporting de Gijón",
        "Burgos CF",
        "SD Eibar",
        "Cádiz CF",
        "Albacete Balompié",
        "CD Castellón",
        "Málaga CF",
        "Real Oviedo",
        "CD Mirandés",
        "CD Eldense",
        "Racing de Ferrol",
        "RC Deportivo",
        "UD Almería",
        "Racing de Santander"
    ],
    "Germany 1. Bundesliga (1)": [
        "Bayer 04 Leverkusen",
        "Borussia M'gladbach",
        "VfL Bochum",
        "Borussia Dortmund",
        "VfB Stuttgart",
        "TSG 1899 Hoffenheim",
        "VfL Wolfsburg",
        "FC Augsburg",
        "1. FSV Mainz 05",
        "Holstein Kiel",
        "FC St. Pauli",
        "Werder Bremen",
        "1. FC Union Berlin",
        "SC Freiburg"
    ],
    "Italy Serie A (1)": [
        "Cagliari",
        "Lecce",
        "Monza",
        "Empoli",
        "Torino",
        "Bologna",
        "Genoa",
        "Parma",
        "Hellas Verona",
        "Milano FC",
        "Lazio",
        "Venezia",
        "Juventus",
        "Atalanta",
        "Como",
        "Fiorentina",
        "Lombardia FC",
        "Roma"
    ],
    "China Super League (1)": [
        "Shenzhen Peng City",
        "Qingdao West Coast FC",
        "Meizhou Hakka",
        "Shanghai Port",
        "Henan FC",
        "Wuhan Three Towns",
        "Cangzhou Mighty Lions",
        "Qingdao Hainiu FC",
        "Tianjin Jinmen Tiger",
        "Shanghai Shenhua",
        "Beijing Guoan",
        "Changchun Yatai",
        "Nantong Zhiyun",
        "Shandong Taishan",
        "Chengdu Rongcheng F.C.",
        "Zhejiang Professional FC"
    ],
    "Sweden Allsvenskan (1)": [
        "Västerås SK",
        "Djurgårdens IF",
        "GAIS",
        "IF Brommapojkarna",
        "IF Elfsborg",
        "BK Häcken",
        "Halmstads BK",
        "Mjällby AIF",
        "IFK Värnamo",
        "IK Sirius",
        "AIK",
        "Hammarby IF",
        "Malmö FF",
        "IFK Göteborg",
        "Kalmar FF",
        "IFK Norrköping"
    ],
    "Poland Ekstraklasa (1)": [
        "Lech Poznań",
        "GKS Katowice",
        "Widzew Łódź",
        "Radomiak Radom",
        "Legia Warszawa",
        "Śląsk Wrocław",
        "Lechia Gdańsk",
        "Motor Lublin",
        "Korona Kielce",
        "Puszcza Niepołomice",
        "Cracovia",
        "Raków Częstochowa",
        "Pogoń Szczecin",
        "Stal Mielec",
        "Zagłębie Lubin",
        "Górnik Zabrze",
        "Piast Gliwice",
        "Jagiellonia Białystok"
    ],
    "Belgium Pro League (1)": [
        "Cercle Brugge",
        "Gent",
        "Genk",
        "Charleroi",
        "Union Saint-Gilloise",
        "OH Leuven",
        "Club Brugge",
        "Sint-Truiden",
        "Beerschot",
        "Dender",
        "Antwerp",
        "Standard Liège",
        "Westerlo",
        "KV Mechelen",
        "Kortrijk",
        "Anderlecht"
    ],
    "England League One (3)": [
        "Burton Albion",
        "Cambridge United",
        "Rotherham United",
        "Bristol Rovers",
        "Peterborough United",
        "Barnsley",
        "Stevenage",
        "Exeter City",
        "Northampton Town",
        "Charlton Athletic",
        "Crawley Town",
        "Stockport County",
        "Wigan Athletic",
        "Wrexham",
        "Reading",
        "Mansfield Town",
        "Leyton Orient",
        "Birmingham City",
        "Wycombe Wanderers",
        "Shrewsbury Town",
        "Lincoln City",
        "Blackpool",
        "Bolton Wanderers",
        "Huddersfield Town"
    ],
    "Switzerland Super League (1)": [
        "FC Zürich",
        "BSC Young Boys",
        "FC Lugano",
        "FC St. Gallen",
        "FC Lausanne-Sport",
        "Servette FC",
        "FC Winterthur",
        "FC Luzern",
        "FC Sion",
        "Yverdon-Sport",
        "Grasshopper Club Zürich",
        "FC Basel"
    ],
    "Romania Liga I (1)": [
        "Dinamo București",
        "Universitatea Craiova",
        "Sepsi OSK",
        "Rapid București",
        "FC Botoșani",
        "ASC Oțelul Galați",
        "Gloria Buzău",
        "FC Hermannstadt",
        "Politehnica Iași",
        "Petrolul Ploiești",
        "Unirea Slobozia",
        "Universitatea Cluj",
        "CFR Cluj",
        "UTA Arad",
        "Farul Constanța",
        "FCSB"
    ],
    "Italy Serie B (2)": [
        "Carrarese",
        "Sampdoria",
        "Cosenza",
        "Frosinone",
        "Salernitana",
        "Sassuolo",
        "Modena",
        "Juve Stabia",
        "Cittadella",
        "Cesena",
        "Mantova",
        "Reggiana",
        "Bari",
        "Catanzaro",
        "Pisa",
        "Palermo",
        "Cremonese",
        "Südtirol",
        "Brescia",
        "Spezia"
    ],
    "England Premier League (1)": [
        "Leicester City",
        "Fulham",
        "Manchester City",
        "Liverpool",
        "Wolverhampton Wanderers",
        "Nottingham Forest",
        "Chelsea",
        "Manchester United",
        "Tottenham Hotspur",
        "West Ham United",
        "Crystal Palace",
        "Aston Villa",
        "Everton",
        "Brentford",
        "Brighton & Hove Albion",
        "Ipswich Town",
        "Newcastle United",
        "Arsenal",
        "AFC Bournemouth",
        "Southampton"
    ],
    "Denmark Superliga (1)": [
        "AGF",
        "Vejle BK",
        "FC København",
        "Randers FC",
        "Silkeborg IF",
        "FC Nordsjælland",
        "Brøndby IF",
        "Viborg FF",
        "Lyngby BK",
        "AaB",
        "Sønderjyske Fodbold",
        "FC Midtjylland"
    ],
    "Germany 3. Liga (3)": [
        "TSV 1860 München",
        "Viktoria Köln",
        "Erzgebirge Aue",
        "Hannover 96 II",
        "Hansa Rostock",
        "FC Ingolstadt 04",
        "Rot-Weiß Essen",
        "Borussia Dortmund II",
        "SpVgg Unterhaching",
        "SC Verl",
        "VfB Stuttgart II",
        "Energie Cottbus",
        "Alemannia Aachen",
        "1. FC Saarbrücken",
        "VfL Osnabrück",
        "SV Wehen Wiesbaden",
        "SV Waldhof Mannheim",
        "SV Sandhausen",
        "Dynamo Dresden",
        "Arminia Bielefeld"
    ],
    "Croatia Prva HNL (1)": [
        "Dinamo Zagreb",
        "Hajduk Split"
    ],
    "Portugal Primeira Liga (1)": [
        "Casa Pia",
        "Estrela da Amadora",
        "Vitória de Guimarães",
        "Braga",
        "Estoril",
        "Rio Ave",
        "Gil Vicente FC",
        "Arouca",
        "Moreirense",
        "Famalicão",
        "Sporting CP",
        "Farense",
        "FC Porto",
        "Benfica",
        "AVS Futebol SAD",
        "Nacional da Madeira",
        "Santa Clara",
        "Boavista"
    ],
    "Korea K League 1 (1)": [
        "Gwangju FC",
        "Jeju United",
        "Daejeon Hana Citizen",
        "Suwon FC",
        "Daegu FC",
        "Incheon United",
        "Pohang Steelers",
        "FC Seoul",
        "Gangwon FC",
        "Jeonbuk Hyundai Motors",
        "Ulsan HD FC",
        "Gimcheon Sangmu"
    ],
    "Rep. Ireland Premier Division (1)": [
        "Bohemians",
        "Sligo Rovers",
        "Drogheda United",
        "Dundalk",
        "St Patrick's Athletic",
        "Galway United",
        "Shamrock Rovers",
        "Waterford",
        "Derry City",
        "Shelbourne"
    ],
    "Indian Super League (1)": [
        "NorthEast United",
        "Odisha FC",
        "Hyderabad FC",
        "Mumbai City FC",
        "East Bengal FC",
        "Mohun Bagan Super Giant",
        "Kerala Blasters FC",
        "Mohammedan SC",
        "Jamshedpur FC",
        "Punjab FC",
        "FC Goa",
        "Chennaiyin FC",
        "Bengaluru FC"
    ],
    "Ukraine Premier Liga (1)": [
        "Shakhtar Donetsk",
        "Dynamo Kyiv"
    ],
    "Saudi Pro League (1)": [
        "Al Fateh",
        "Al Raed",
        "Al Ettifaq",
        "Al Riyadh",
        "Al Fayha",
        "Al Shabab",
        "Al Nassr",
        "Al Ittihad",
        "Al Kholood",
        "Al Taawoun",
        "Al Orobah",
        "Al Wehda",
        "Al Khaleej",
        "Al Qadsiah",
        "Al Okhdood",
        "Al Ahli",
        "Damac FC",
        "Al Hilal"
    ],
    "Austria Bundesliga (1)": [
        "Blau-Weiß Linz",
        "Wolfsberger AC",
        "SCR Altach",
        "Sturm Graz",
        "SK Rapid",
        "Austria Klagenfurt",
        "Grazer AK",
        "Austria Wien",
        "Hartberg",
        "WSG Tirol",
        "LASK",
        "RB Salzburg"
    ],
    "Scotland Premiership (1)": [
        "St. Johnstone",
        "Ross County",
        "Kilmarnock",
        "Dundee United",
        "Rangers",
        "Heart of Midlothian",
        "Motherwell",
        "Aberdeen",
        "Celtic",
        "St. Mirren",
        "Dundee FC",
        "Hibernian"
    ],
    "FUT Magyar Liga": [
        "Ferencvárosi TC"
    ],
    "Czech Republic Liga (1)": [
        "Sparta Praha",
        "Viktoria Plzeň",
        "Slavia Praha"
    ],
    "UAE FUT League": [
        "Al Ain FC (UAE)"
    ],
    "Finland Veikkausliiga (1)": [
        "HJK Helsinki"
    ],
    "Greece A'Ethniki (1)": [
        "Olympiacos",
        "PAOK",
        "AEK",
        "Panathinaikos"
    ],
    "FUT Liga Azerbaijan": [
        "Qarabağ FK"
    ],
    "FUT Liga Cyprus": [
        "APOEL Nicosia FC"
    ],
    "International": [
        "Mexico",
        "Qatar",
        "Hungary",
        "Ghana",
        "Iceland",
        "Spain",
        "Morocco",
        "Korea Republic",
        "United States",
        "Poland",
        "New Zealand",
        "Finland",
        "Czech Republic"
    ],
    "FUT Liga Colombia": [
        "Atlético Nacional"
    ],
    "CONMEBOL Sudamericana": [
        "Delfín SC",
        "Always Ready",
        "Racing Club De Montevideo",
        "Sportivo Luqueño",
        "Técnico Universitario",
        "Universitario de Vinto",
        "Deportivo Cuenca",
        "Danubio FC",
        "Guaraní (Paraguay)",
        "Unión La Calera",
        "Deportivo Garcilaso",
        "Asociación Deportiva Tarma",
        "Independiente Medellín",
        "Rayo Zuliano",
        "Deportivo La Guaira",
        "Carabobo FC",
        "Metropolitanos FC",
        "Nacional Asunción",
        "Sportivo Trinidense",
        "Sport Huancayo",
        "Cerro Largo",
        "Coquimbo Unido",
        "Real Tomayapo",
        "Alianza FC",
        "Olimpia Asunción",
        "Deportes Tolima",
        "Jorge Wilstermann",
        "Sportivo Ameliano",
        "Montevideo Wanderers",
        "América de Cali",
        "Nacional Potosí",
        "Universidad Católica del Ecuador",
        "Everton de Viña del Mar",
        "Universidad Católica",
        "Universidad César Vallejo",
        "Fortaleza",
        "Corinthians",
        "RB Bragantino",
        "Cuiabá",
        "Internacional",
        "Cruzeiro",
        "Athletico Paranaense"
    ],
    "CONMEBOL Libertadores": [
        "Deportivo Táchira",
        "LDU Quito",
        "Cerro Porteño",
        "Nacional de Montevideo",
        "Palestino",
        "Caracas FC",
        "Colo-Colo",
        "Independiente del Valle",
        "Barcelona SC Guayaquil",
        "Huachipato",
        "Bolívar",
        "Cobresal",
        "Junior de Barranquilla",
        "Millonarios",
        "Universitario de Deportes",
        "Alianza Lima",
        "Peñarol",
        "The Strongest",
        "Liverpool Fútbol Club Uruguay",
        "Libertad",
        "Grêmio",
        "Atlético Mineiro",
        "Palmeiras",
        "Botafogo",
        "Flamengo",
        "Fluminense",
        "São Paulo"
    ]
};