const countryData = [{"name":"요르단","logos":"https://flagcdn.com/jo.svg"},{"name":"북마리아나 제도","logos":"https://flagcdn.com/mp.svg"},{"name":"세르비아","logos":"https://flagcdn.com/rs.svg"},{"name":"안도라","logos":"https://flagcdn.com/ad.svg"},{"name":"터크스 케이커스 제도","logos":"https://flagcdn.com/tc.svg"},{"name":"버뮤다","logos":"https://flagcdn.com/bm.svg"},{"name":"남극","logos":"https://flagcdn.com/aq.svg"},{"name":"볼리비아","logos":"https://flagcdn.com/bo.svg"},{"name":"리비아","logos":"https://flagcdn.com/ly.svg"},{"name":"말리","logos":"https://flagcdn.com/ml.svg"},{"name":"아르메니아","logos":"https://flagcdn.com/am.svg"},{"name":"모리셔스","logos":"https://flagcdn.com/mu.svg"},{"name":"몰디브","logos":"https://flagcdn.com/mv.svg"},{"name":"아메리칸사모아","logos":"https://flagcdn.com/as.svg"},{"name":"북마케도니아","logos":"https://flagcdn.com/mk.svg"},{"name":"에티오피아","logos":"https://flagcdn.com/et.svg"},{"name":"그린란드","logos":"https://flagcdn.com/gl.svg"},{"name":"이라크","logos":"https://flagcdn.com/iq.svg"},{"name":"과테말라","logos":"https://flagcdn.com/gt.svg"},{"name":"트리니다드 토바고","logos":"https://flagcdn.com/tt.svg"},{"name":"페루","logos":"https://flagcdn.com/pe.svg"},{"name":"수리남","logos":"https://flagcdn.com/sr.svg"},{"name":"스웨덴","logos":"https://flagcdn.com/se.svg"},{"name":"누벨칼레도니","logos":"https://flagcdn.com/nc.svg"},{"name":"프랑스령 폴리네시아","logos":"https://flagcdn.com/pf.svg"},{"name":"베냉","logos":"https://flagcdn.com/bj.svg"},{"name":"에스토니아","logos":"https://flagcdn.com/ee.svg"},{"name":"포클랜드 제도","logos":"https://flagcdn.com/fk.svg"},{"name":"괌","logos":"https://flagcdn.com/gu.svg"},{"name":"짐바브웨","logos":"https://flagcdn.com/zw.svg"},{"name":"슬로바키아","logos":"https://flagcdn.com/sk.svg"},{"name":"네덜란드","logos":"https://flagcdn.com/nl.svg"},{"name":"에콰도르","logos":"https://flagcdn.com/ec.svg"},{"name":"사우디아라비아","logos":"https://flagcdn.com/sa.svg"},{"name":"아랍에미리트","logos":"https://flagcdn.com/ae.svg"},{"name":"아프가니스탄","logos":"https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg"},{"name":"미국령 군소 제도","logos":"https://flagcdn.com/um.svg"},{"name":"중앙아프리카 공화국","logos":"https://flagcdn.com/cf.svg"},{"name":"파나마","logos":"https://flagcdn.com/pa.svg"},{"name":"바티칸","logos":"https://flagcdn.com/va.svg"},{"name":"시리아","logos":"https://flagcdn.com/sy.svg"},{"name":"바누아투","logos":"https://flagcdn.com/vu.svg"},{"name":"온두라스","logos":"https://flagcdn.com/hn.svg"},{"name":"키리바시","logos":"https://flagcdn.com/ki.svg"},{"name":"칠레","logos":"https://flagcdn.com/cl.svg"},{"name":"부르키나파소","logos":"https://flagcdn.com/bf.svg"},{"name":"세인트키츠 네비스","logos":"https://flagcdn.com/kn.svg"},{"name":"생바르텔레미","logos":"https://flagcdn.com/bl.svg"},{"name":"멕시코","logos":"https://flagcdn.com/mx.svg"},{"name":"중국","logos":"https://flagcdn.com/cn.svg"},{"name":"동티모르","logos":"https://flagcdn.com/tl.svg"},{"name":"인도","logos":"https://flagcdn.com/io.svg"},{"name":"남수단","logos":"https://flagcdn.com/ss.svg"},{"name":"에스와티니","logos":"https://flagcdn.com/sz.svg"},{"name":"우즈베키스탄","logos":"https://flagcdn.com/uz.svg"},{"name":"인도네시아","logos":"https://flagcdn.com/id.svg"},{"name":"파라과이","logos":"https://flagcdn.com/py.svg"},{"name":"모나코","logos":"https://flagcdn.com/mc.svg"},{"name":"그레나다","logos":"https://flagcdn.com/gd.svg"},{"name":"크로아티아","logos":"https://flagcdn.com/hr.svg"},{"name":"폴란드","logos":"https://flagcdn.com/pl.svg"},{"name":"보스니아 헤르체고비나","logos":"https://flagcdn.com/ba.svg"},{"name":"캐나다","logos":"https://flagcdn.com/ca.svg"},{"name":"포르투갈","logos":"https://flagcdn.com/pt.svg"},{"name":"브라질","logos":"https://flagcdn.com/br.svg"},{"name":"모리타니","logos":"https://flagcdn.com/mr.svg"},{"name":"이스라엘","logos":"https://flagcdn.com/il.svg"},{"name":"퀴라소","logos":"https://flagcdn.com/cw.svg"},{"name":"브루나이","logos":"https://flagcdn.com/bn.svg"},{"name":"앙골라","logos":"https://flagcdn.com/ao.svg"},{"name":"몰타","logos":"https://flagcdn.com/mt.svg"},{"name":"벨라루스","logos":"https://flagcdn.com/by.svg"},{"name":"터키","logos":"https://flagcdn.com/tr.svg"},{"name":"핀란드","logos":"https://flagcdn.com/fi.svg"},{"name":"지브롤터","logos":"https://flagcdn.com/gi.svg"},{"name":"부탄","logos":"https://flagcdn.com/bt.svg"},{"name":"스페인","logos":"https://flagcdn.com/es.svg"},{"name":"베네수엘라","logos":"https://flagcdn.com/ve.svg"},{"name":"카타르","logos":"https://flagcdn.com/qa.svg"},{"name":"체코","logos":"https://flagcdn.com/cz.svg"},{"name":"쿠웨이트","logos":"https://flagcdn.com/kw.svg"},{"name":"몬테네그로","logos":"https://flagcdn.com/me.svg"},{"name":"부베 섬","logos":"https://flagcdn.com/bv.svg"},{"name":"인도","logos":"https://flagcdn.com/in.svg"},{"name":"뉴질랜드","logos":"https://flagcdn.com/nz.svg"},{"name":"자메이카","logos":"https://flagcdn.com/jm.svg"},{"name":"케이맨 제도","logos":"https://flagcdn.com/ky.svg"},{"name":"산마리노","logos":"https://flagcdn.com/sm.svg"},{"name":"콩고","logos":"https://flagcdn.com/cg.svg"},{"name":"파키스탄","logos":"https://flagcdn.com/pk.svg"},{"name":"프랑스","logos":"https://flagcdn.com/fr.svg"},{"name":"카자흐스탄","logos":"https://flagcdn.com/kz.svg"},{"name":"바레인","logos":"https://flagcdn.com/bh.svg"},{"name":"피지","logos":"https://flagcdn.com/fj.svg"},{"name":"아이슬란드","logos":"https://flagcdn.com/is.svg"},{"name":"미얀마","logos":"https://flagcdn.com/mm.svg"},{"name":"방글라데시","logos":"https://flagcdn.com/bd.svg"},{"name":"필리핀","logos":"https://flagcdn.com/ph.svg"},{"name":"적도 기니","logos":"https://flagcdn.com/gq.svg"},{"name":"아일랜드","logos":"https://flagcdn.com/ie.svg"},{"name":"네팔","logos":"https://flagcdn.com/np.svg"},{"name":"예멘","logos":"https://flagcdn.com/ye.svg"},{"name":"대한민국","logos":"https://flagcdn.com/kr.svg"},{"name":"덴마크","logos":"https://flagcdn.com/dk.svg"},{"name":"오만","logos":"https://flagcdn.com/om.svg"},{"name":"세인트빈센트 그레나딘","logos":"https://flagcdn.com/vc.svg"},{"name":"에리트레아","logos":"https://flagcdn.com/er.svg"},{"name":"호주","logos":"https://flagcdn.com/au.svg"},{"name":"이란","logos":"https://flagcdn.com/ir.svg"},{"name":"엘살바도르","logos":"https://flagcdn.com/sv.svg"},{"name":"탄자니아","logos":"https://flagcdn.com/tz.svg"},{"name":"과들루프","logos":"https://flagcdn.com/gp.svg"},{"name":"솔로몬 제도","logos":"https://flagcdn.com/sb.svg"},{"name":"케냐","logos":"https://flagcdn.com/ke.svg"},{"name":"도미니카 공화국","logos":"https://flagcdn.com/do.svg"},{"name":"그리스","logos":"https://flagcdn.com/gr.svg"},{"name":"건지 섬","logos":"https://flagcdn.com/gg.svg"},{"name":"르완다","logos":"https://flagcdn.com/rw.svg"},{"name":"생피에르 미클롱","logos":"https://flagcdn.com/pm.svg"},{"name":"투발루","logos":"https://flagcdn.com/tv.svg"},{"name":"대만","logos":"https://flagcdn.com/tw.svg"},{"name":"가이아나","logos":"https://flagcdn.com/gy.svg"},{"name":"세이셸","logos":"https://flagcdn.com/sc.svg"},{"name":"북한","logos":"https://flagcdn.com/kp.svg"},{"name":"보츠와나","logos":"https://flagcdn.com/bw.svg"},{"name":"캄보디아","logos":"https://flagcdn.com/kh.svg"},{"name":"바베이도스","logos":"https://flagcdn.com/bb.svg"},{"name":"콜롬비아","logos":"https://flagcdn.com/co.svg"},{"name":"우크라이나","logos":"https://flagcdn.com/ua.svg"},{"name":"코트디부아르","logos":"https://flagcdn.com/ci.svg"},{"name":"나우루","logos":"https://flagcdn.com/nr.svg"},{"name":"나미비아","logos":"https://flagcdn.com/na.svg"},{"name":"차드","logos":"https://flagcdn.com/td.svg"},{"name":"통가","logos":"https://flagcdn.com/to.svg"},{"name":"아르헨티나","logos":"https://flagcdn.com/ar.svg"},{"name":"크리스마스 섬","logos":"https://flagcdn.com/cx.svg"},{"name":"니제르","logos":"https://flagcdn.com/ne.svg"},{"name":"마셜 제도","logos":"https://flagcdn.com/mh.svg"},{"name":"코스타리카","logos":"https://flagcdn.com/cr.svg"},{"name":"가나","logos":"https://flagcdn.com/gh.svg"},{"name":"오스트리아","logos":"https://flagcdn.com/at.svg"},{"name":"세인트헬레나","logos":"https://flagcdn.com/sh.svg"},{"name":"팔레스타인","logos":"https://flagcdn.com/ps.svg"},{"name":"쿠바","logos":"https://flagcdn.com/cu.svg"},{"name":"헝가리","logos":"https://flagcdn.com/hu.svg"},{"name":"미크로네시아","logos":"https://flagcdn.com/fm.svg"},{"name":"벨리즈","logos":"https://flagcdn.com/bz.svg"},{"name":"바하마","logos":"https://flagcdn.com/bs.svg"},{"name":"아루바","logos":"https://flagcdn.com/aw.svg"},{"name":"상투메 프린시페","logos":"https://flagcdn.com/st.svg"},{"name":"러시아","logos":"https://flagcdn.com/ru.svg"},{"name":"룩셈부르크","logos":"https://flagcdn.com/lu.svg"},{"name":"페로 제도","logos":"https://flagcdn.com/fo.svg"},{"name":"니카라과","logos":"https://flagcdn.com/ni.svg"},{"name":"튀니지","logos":"https://flagcdn.com/tn.svg"},{"name":"콩고 민주 공화국","logos":"https://flagcdn.com/cd.svg"},{"name":"스발바르 얀마옌 제도","logos":"https://flagcdn.com/sj.svg"},{"name":"남아프리카","logos":"https://flagcdn.com/za.svg"},{"name":"시에라리온","logos":"https://flagcdn.com/sl.svg"},{"name":"레소토","logos":"https://flagcdn.com/ls.svg"},{"name":"조지아","logos":"https://flagcdn.com/gs.svg"},{"name":"이탈리아","logos":"https://flagcdn.com/it.svg"},{"name":"지부티","logos":"https://flagcdn.com/dj.svg"},{"name":"허드 맥도널드 제도","logos":"https://flagcdn.com/hm.svg"},{"name":"스리랑카","logos":"https://flagcdn.com/lk.svg"},{"name":"세인트루시아","logos":"https://flagcdn.com/lc.svg"},{"name":"사모아","logos":"https://flagcdn.com/ws.svg"},{"name":"코코스 제도","logos":"https://flagcdn.com/cc.svg"},{"name":"푸에르토리코","logos":"https://flagcdn.com/pr.svg"},{"name":"가봉","logos":"https://flagcdn.com/ga.svg"},{"name":"투르크메니스탄","logos":"https://flagcdn.com/tm.svg"},{"name":"라트비아","logos":"https://flagcdn.com/lv.svg"},{"name":"세네갈","logos":"https://flagcdn.com/sn.svg"},{"name":"벨기에","logos":"https://flagcdn.com/be.svg"},{"name":"몰도바","logos":"https://flagcdn.com/md.svg"},{"name":"리히텐슈타인","logos":"https://flagcdn.com/li.svg"},{"name":"말라위","logos":"https://flagcdn.com/mw.svg"},{"name":"레바논","logos":"https://flagcdn.com/lb.svg"},{"name":"몽골국","logos":"https://flagcdn.com/mn.svg"},{"name":"노르웨이","logos":"https://flagcdn.com/no.svg"},{"name":"영국령 버진아일랜드","logos":"https://flagcdn.com/vg.svg"},{"name":"카메룬","logos":"https://flagcdn.com/cm.svg"},{"name":"태국","logos":"https://flagcdn.com/th.svg"},{"name":"나이지리아","logos":"https://flagcdn.com/ng.svg"},{"name":"레위니옹","logos":"https://flagcdn.com/re.svg"},{"name":"카보베르데","logos":"https://flagcdn.com/cv.svg"},{"name":"저지 섬","logos":"https://flagcdn.com/je.svg"},{"name":"알제리","logos":"https://flagcdn.com/dz.svg"},{"name":"라오스","logos":"https://flagcdn.com/la.svg"},{"name":"카리브 네덜란드","logos":"https://flagcdn.com/bq.svg"},{"name":"아제르바이잔","logos":"https://flagcdn.com/az.svg"},{"name":"신트마르턴","logos":"https://flagcdn.com/sx.svg"},{"name":"모로코","logos":"https://flagcdn.com/ma.svg"},{"name":"올란드 제도","logos":"https://flagcdn.com/ax.svg"},{"name":"불가리아","logos":"https://flagcdn.com/bg.svg"},{"name":"부룬디","logos":"https://flagcdn.com/bi.svg"},{"name":"우간다","logos":"https://flagcdn.com/ug.svg"},{"name":"코소보","logos":"https://flagcdn.com/xk.svg"},{"name":"모잠비크","logos":"https://flagcdn.com/mz.svg"},{"name":"조지아","logos":"https://flagcdn.com/ge.svg"},{"name":"영국","logos":"https://flagcdn.com/gb.svg"},{"name":"왈리스 퓌튀나","logos":"https://flagcdn.com/wf.svg"},{"name":"핏케언 제도","logos":"https://flagcdn.com/pn.svg"},{"name":"루마니아","logos":"https://flagcdn.com/ro.svg"},{"name":"베트남","logos":"https://flagcdn.com/vn.svg"},{"name":"프랑스령 남부와 남극 지역","logos":"https://flagcdn.com/tf.svg"},{"name":"서사하라","logos":"https://flagcdn.com/eh.svg"},{"name":"일본","logos":"https://flagcdn.com/jp.svg"},{"name":"이집트","logos":"https://flagcdn.com/eg.svg"},{"name":"라이베리아","logos":"https://flagcdn.com/lr.svg"},{"name":"리투아니아","logos":"https://flagcdn.com/lt.svg"},{"name":"아이티","logos":"https://flagcdn.com/ht.svg"},{"name":"미국령 버진아일랜드","logos":"https://flagcdn.com/vi.svg"},{"name":"파푸아뉴기니","logos":"https://flagcdn.com/pg.svg"},{"name":"홍콩","logos":"https://flagcdn.com/hk.svg"},{"name":"키르기스스탄","logos":"https://flagcdn.com/kg.svg"},{"name":"팔라우","logos":"https://flagcdn.com/pw.svg"},{"name":"마다가스카르","logos":"https://flagcdn.com/mg.svg"},{"name":"감비아","logos":"https://flagcdn.com/gm.svg"},{"name":"토고","logos":"https://flagcdn.com/tg.svg"},{"name":"토켈라우","logos":"https://flagcdn.com/tk.svg"},{"name":"슬로베니아","logos":"https://flagcdn.com/si.svg"},{"name":"싱가포르","logos":"https://flagcdn.com/sg.svg"},{"name":"프랑스령 기아나","logos":"https://flagcdn.com/gf.svg"},{"name":"미국","logos":"https://flagcdn.com/us.svg"},{"name":"몬트세랫","logos":"https://flagcdn.com/ms.svg"},{"name":"말레이시아","logos":"https://flagcdn.com/my.svg"},{"name":"독일","logos":"https://flagcdn.com/de.svg"},{"name":"앤티가 바부다","logos":"https://flagcdn.com/ag.svg"},{"name":"생마르탱","logos":"https://flagcdn.com/mf.svg"},{"name":"소말리아","logos":"https://flagcdn.com/so.svg"},{"name":"마카오","logos":"https://flagcdn.com/mo.svg"},{"name":"알바니아","logos":"https://flagcdn.com/al.svg"},{"name":"마요트","logos":"https://flagcdn.com/yt.svg"},{"name":"도미니카 공화국","logos":"https://flagcdn.com/dm.svg"},{"name":"잠비아","logos":"https://flagcdn.com/zm.svg"},{"name":"앵귈라","logos":"https://flagcdn.com/ai.svg"},{"name":"쿡 제도","logos":"https://flagcdn.com/ck.svg"},{"name":"마르티니크","logos":"https://flagcdn.com/mq.svg"},{"name":"기니","logos":"https://flagcdn.com/gn.svg"},{"name":"코모로","logos":"https://flagcdn.com/km.svg"},{"name":"니우에","logos":"https://flagcdn.com/nu.svg"},{"name":"스위스","logos":"https://flagcdn.com/ch.svg"},{"name":"노퍽 섬","logos":"https://flagcdn.com/nf.svg"},{"name":"맨섬","logos":"https://flagcdn.com/im.svg"},{"name":"수단","logos":"https://flagcdn.com/sd.svg"},{"name":"타지키스탄","logos":"https://flagcdn.com/tj.svg"},{"name":"우루과이","logos":"https://flagcdn.com/uy.svg"},{"name":"키프로스","logos":"https://flagcdn.com/cy.svg"},{"name":"기니비사우","logos":"https://flagcdn.com/gw.svg"},{"name":"잉글랜드","logos":"https://indvel.github.io/utils/fsm/logos/OtherFlags/Flag_of_England.svg"},{"name":"스코틀랜드","logos":"https://indvel.github.io/utils/fsm/logos/OtherFlags/Flag_of_Scotland.svg"},{"name":"웨일스","logos":"https://indvel.github.io/utils/fsm/logos/OtherFlags/Flag_of_Wales.svg"},{"name":"북아일랜드","logos":"https://indvel.github.io/utils/fsm/logos/OtherFlags/Flag_of_NorthernIreland.svg"}];
const KLeague = [
	{"name": "강원 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Gangwon_FC.svg", "shortName": "강원"},
	{"name": "광주 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Gwangju_FC.svg", "shortName": "광주"},
	{"name": "대구 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Daegu_FC.svg", "shortName": "대구"},
	{"name": "대전 하나 시티즌", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Daejeon_Hana_Citizen.svg", "shortName": "대전 하나"},
	{"name": "FC 서울", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/FC_Seoul_logo.svg", "shortName": "서울"},
	{"name": "수원 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Suwon_FC.svg", "shortName": "수원"},
	{"name": "울산 HD FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Ulsan_HD_FC.svg", "shortName": "울산"},
	{"name": "전북 현대 모터스", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Jeonbuk_Hyundai_Motors.svg", "shortName": "전북"},
	{"name": "제주 SK FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Jeju_SK_FC.svg", "shortName": "제주"},
	{"name": "포항 스틸러스", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Pohang_Steelers.svg", "shortName": "포항"},
	{"name": "FC 안양", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/FCAnyang.svg", "shortName": "안양"},
	{"name": "부천 FC 1995", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/BucheonFC1995.svg", "shortName": "부천"},
	{"name": "김천 상무 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague/Gimcheon_Sangmu_FC.svg", "shortName": "김천 상무"}
];

const KLeague2 = [
	{"name": "안산 그리너스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/AnsanGreenersFC.svg", "shortName": "안산"},
	{"name": "부산 아이파크", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/BusanIPark.svg", "shortName": "부산 IP"},
	{"name": "천안 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/CheonanCityFC.svg", "shortName": "천안 시티"},
	{"name": "충북 청주 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/ChungbukCheongjuFC.svg", "shortName": "충북 청주"},
	{"name": "충남 아산 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/ChungnamAsanFC.svg", "shortName": "충남 아산"},
	{"name": "김포 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/GimpoFC.svg", "shortName": "김포"},
	{"name": "경남 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/GyeongnamFC.svg", "shortName": "경남"},
	{"name": "화성 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/HwaseongFC.svg", "shortName": "화성"},
	{"name": "인천 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/Incheon_United_FC.svg", "shortName": "인천"},
	{"name": "전남 드래곤즈", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/JeonnamDragons.svg", "shortName": "전남"},
	{"name": "성남 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/SeongnamFC.svg", "shortName": "성남"},
	{"name": "서울 이랜드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/SeoulE-LandFC.svg", "shortName": "서울 이랜드"},
	{"name": "수원 삼성 블루윙즈", "logos": "https://indvel.github.io/utils/fsm/logos/KLeague2/SuwonSamsungBluewings.svg", "shortName": "수원삼성"}
];

const EPL = [
	{"name": "노팅엄 포레스트 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Nottingham_Forest_F.C._logo.svg", "shortName": "노팅엄"},
	{"name": "뉴캐슬 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Newcastle_United_Logo.svg", "shortName": "뉴캐슬"},
	{"name": "루턴 타운 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Luton_Town_FC.svg", "shortName": "루턴 타운"},
	{"name": "리버풀 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Liverpool_FC_New.svg", "shortName": "리버풀"},
	{"name": "맨체스터 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Manchester_City_FC.svg", "shortName": "맨시티"},
	{"name": "맨체스터 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Manchester_United_FC.svg", "shortName": "맨유"},
	{"name": "번리 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Burnley_FC_Logo.svg", "shortName": "번리"},
	{"name": "AFC 본머스", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/AFC_Bournemouth.svg", "shortName": "본머스"},
	{"name": "브라이튼 앤 호브 알비온 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Brighton_And_Hove_Albion_logo.svg", "shortName": "브라이튼"},
	{"name": "브렌트포드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Brentford_FC.svg", "shortName": "브렌트포드"},
	{"name": "아스날 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Arsenal_FC.svg", "shortName": "아스날"},
	{"name": "아스톤 빌라 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Aston_Villa_FC_New.svg", "shortName": "아스톤 빌라"},
	{"name": "에버튼 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Everton_FC_logo.svg", "shortName": "에버튼"},
	{"name": "울버햄튼 원더러스", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Wolverhampton_Wanderers.svg", "shortName": "울버햄튼"},
	{"name": "웨스트햄 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/West_Ham_United_FC_logo.svg", "shortName": "웨스트햄"},
	{"name": "첼시 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Chelsea_FC.svg", "shortName": "첼시"},
	{"name": "토트넘 홋스퍼 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Tottenham_Hotspur.svg", "shortName": "토트넘"},
	{"name": "크리스탈 팰리스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Crystal_Palace_FC_logo.svg", "shortName": "C.팰리스"},
	{"name": "풀럼 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Fulham_FC.svg", "shortName": "풀럼"},
	{"name": "리즈 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Leeds_United_FC.svg", "shortName": "리즈"},
	{"name": "선덜랜드 AFC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Sunderland_AFC.svg", "shortName": "선덜랜드"}
];
const Bundesliga = [
	{"name": "SV 다름슈타트 98", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/SV_Darmstadt_98_Logo.svg", "shortName": "다름슈타트"},
	{"name": "보루시아 도르트문트", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/Borussia_Dortmund.svg", "shortName": "도르트문트"},
	{"name": "RB 라이프치히", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/RB_Leipzig_logo.svg", "shortName": "라이프치히"},
	{"name": "바이어 04 레버쿠젠", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/Bayer_04_Leverkusen.svg", "shortName": "레버쿠젠"},
	{"name": "1. FSV 마인츠 05", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/1._FSV_Mainz_05.svg", "shortName": "마인츠"},
	{"name": "보루시아 묀헨글라트바흐", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/Borussia_Monchengladbach.svg", "shortName": "묀헨글라트바흐"},
	{"name": "FC 바이에른 뮌헨", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/FC_Bayern_Munchen_logo.svg", "shortName": "B.뮌헨"},
	{"name": "SV 베르더 브레멘", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/SV_Werder_Bremen.svg", "shortName": "베르더 브레멘"},
	{"name": "Vfl 보훔", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/VFL_Bochum.svg", "shortName": "보훔"},
	{"name": "Vfl 볼프스부르크", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/Vfl_Wolfsburg.svg", "shortName": "볼프스부르크"},
	{"name": "VfB 슈투트가르트", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/VfB_Stuttgart.svg", "shortName": "슈투트가르트"},
	{"name": "FC 아우크스부르크", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/FC_Augsburg.svg", "shortName": "아우크스부르크"},
	{"name": "1. FC 우니온 베를린", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/1._FC_Union_Berlin.svg", "shortName": "우니온 베를린"},
	{"name": "1. FC 쾰른", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/1._FC_Koln.svg", "shortName": "쾰른"},
	{"name": "SC 프라이부르크", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/SC_Freiburg.svg", "shortName": "프라이부르크"},
	{"name": "아인트라흐트 프랑크푸르트", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/Eintracht_Frankfurt.svg", "shortName": "프랑크푸르트"},
	{"name": "1. FC 하이덴하임", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/1._FC_Heidenheim.svg", "shortName": "하이덴하임"},
	{"name": "TSG 1899 호펜하임", "logos": "https://indvel.github.io/utils/fsm/logos/Bundesliga/TSG_1899_Hoffenheim.svg", "shortName": "호펜하임"}
];

const Laliga = [
	{"name": "그라나다 CF", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Granada_CF.svg", "shortName": "그라나다"},
	{"name": "UD 라스팔마스", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/UD_Las_Palmas.svg", "shortName": "라스팔마스"},
	{"name": "라요 바예카노", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Rayo_Vallecano.svg", "shortName": "라요 바예카노"},
	{"name": "레알 마드리드 CF", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Real_Madrid_CF.svg", "shortName": "레알 마드리드"},
	{"name": "RCD 마요르카", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/RCD_Mallorca.svg", "shortName": "마요르카"},
	{"name": "FC 바르셀로나", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/FC_Barcelona.svg", "shortName": "바르셀로나"},
	{"name": "발렌시아 CF", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Valencia_CF.svg", "shortName": "발렌시아"},
	{"name": "레알 베티스 발롬피에", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Real_Betis_Balompie.svg", "shortName": "레알 베티스"},
	{"name": "비야레알 CF", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Villarreal_CF.svg", "shortName": "비야레알"},
	{"name": "세비야 FC", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Sevilla_FC.svg", "shortName": "세비야"},
	{"name": "RC 셀타 데 비고", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/RC_Celta_de_Vigo.svg", "shortName": "셀타 비고"},
	{"name": "레알 소시에다드", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Real_Sociedad.svg", "shortName": "R.소시에다드"},
	{"name": "아틀레티코 마드리드", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Atletico_de_Madrid.svg", "shortName": "AT.마드리드"},
	{"name": "아틀레틱 클루브", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Athletic_Club.svg", "shortName": "아틀레틱 클루브"},
	{"name": "데포르티보 알라베스", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Deportivo_Alaves.svg", "shortName": "알라베스"},
	{"name": "UD 알메리아", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/UD_Almeria.svg", "shortName": "알메리아"},
	{"name": "CA 오사수나", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/CA_Osasuna.svg", "shortName": "오사수나"},
	{"name": "지로나 FC", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Girona_FC.svg", "shortName": "지로나"},
	{"name": "카디스 CF", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Cadiz_CF.svg", "shortName": "카디스"},
	{"name": "헤타페 CF", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Getafe_CF.svg", "shortName": "헤타페"},
	{"name": "레알 오비에도", "logos": "https://indvel.github.io/utils/fsm/logos/Laliga/Real_Oviedo.svg", "shortName": "오비에도"}
];

const Ligue1 = [
	{"name": "FC 낭트", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/FC_Nantes.svg", "shortName": "낭트"},
	{"name": "OGC 니스", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/OGC_Nice.svg", "shortName": "OGC 니스"},
	{"name": "RC 랑스", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/RC_Lens.svg", "shortName": "랑스"},
	{"name": "FC 로리앙", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/FC_Lorient.svg", "shortName": "로리앙"},
	{"name": "르아브르 AC", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Le_Havre_AC.svg", "shortName": "르아브르"},
	{"name": "올랭피크 리옹", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Olympique_Lyonnais.svg", "shortName": "리옹"},
	{"name": "LOSC 릴", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/LOSC_Lille.svg", "shortName": "LOSC 릴"},
	{"name": "올랭피크 드 마르세유", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Olympique_de_Marseille.svg", "shortName": "O.마르세유"},
	{"name": "AS 모나코 FC", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/AS_Monaco_FC.svg", "shortName": "AS 모나코"},
	{"name": "몽펠리에 HSC", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Montpellier_HSC.svg", "shortName": "몽펠리에"},
	{"name": "FC 메스", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/FC_Metz.svg", "shortName": "FC 메스"},
	{"name": "스타드 브레스투아 29", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Stade_brestois_29.svg", "shortName": "브레스투아"},
	{"name": "스타드 드 랭스", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Stade_de_Reims.svg", "shortName": "스타드 랭스"},
	{"name": "스타드 렌 FC", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Stade_Rennais_FC.svg", "shortName": "스타드 렌"},
	{"name": "RC 스트라스부르 알자스", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/RC_Strasbourg_Alsace.svg", "shortName": "S.알자스"},
	{"name": "클레르몽 푸트 63", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Clermont_Foot_63.svg", "shortName": "클레르몽 푸트"},
	{"name": "툴루즈 FC", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Toulouse_FC.svg", "shortName": "툴루즈"},
	{"name": "파리 생제르맹 FC", "logos": "https://indvel.github.io/utils/fsm/logos/Ligue1/Paris-Saint-Germain_FC.svg", "shortName": "PSG"}
];

const SerieA = [
	{"name": "SSC 나폴리", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/SSC_Napoli.svg", "shortName": "나폴리"},
	{"name": "SS 라치오", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/SS_Lazio.svg", "shortName": "라치오"},
	{"name": "US 레체", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/US_Lecce.svg", "shortName": "US 레체"},
	{"name": "AS 로마", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/AS_Roma.svg", "shortName": "AS 로마"},
	{"name": "AC 몬차", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/AC_Monza.svg", "shortName": "AC 몬차"},
	{"name": "AC 밀란", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/AC_Milan.svg", "shortName": "AC 밀란"},
	{"name": "엘라스 베로나 FC", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Hellas_Verona_FC.svg", "shortName": "엘라스 베로나"},
	{"name": "볼로냐 FC 1909", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Bologna_FC_1909.svg", "shortName": "볼로냐"},
	{"name": "US 사수올로 칼초", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/US_Sassuolo_Calcio.svg", "shortName": "사수올로 칼초"},
	{"name": "US 살레르니타나 1919", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/US_Salernitana_1919.svg", "shortName": "살레르니타나"},
	{"name": "아탈란타 BC", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Atalanta_BC.svg", "shortName": "아탈란타"},
	{"name": "엠폴리 FC", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Empoli_FC.svg", "shortName": "엠폴리"},
	{"name": "우디네세 칼초", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Udinese_Calcio.svg", "shortName": "우디네세"},
	{"name": "유벤투스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Juventus_FC.svg", "shortName": "유벤투스"},
	{"name": "FC 인테르나치오날레 밀라노", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/FC_Internazionale_Milano.svg", "shortName": "인테르"},
	{"name": "제노아 CFC", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Genoa_CFC.svg", "shortName": "제노아"},
	{"name": "칼리아리 칼초", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Cagliari_Calcio.svg", "shortName": "칼리아리"},
	{"name": "토리노 FC", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Torino_FC.svg", "shortName": "토리노 FC"},
	{"name": "프로시노네 칼초", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/Frosinone_Calcioo.svg", "shortName": "프로시노네"},
	{"name": "ACF 피오렌티나", "logos": "https://indvel.github.io/utils/fsm/logos/SerieA/ACF_Fiorentina.svg", "shortName": "피오렌티나"}
];

const J1League = [
	{"name": "가시마 앤틀러스", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Kashima_Antlers.svg", "shortName": "K.앤틀러스"},
	{"name": "가시와 레이솔", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Kashiwa_Reysol.svg", "shortName": "가시와 레이솔"},
	{"name": "가와사키 프론탈레", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Kawasaki_Frontale.svg", "shortName": "K.프론탈레"},
	{"name": "비셀 고베", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Vissel_Kobe.svg", "shortName": "비셀 고베"},
	{"name": "교토 상가 FC", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Kyoto_Sanga_FC.svg", "shortName": "교토 상가"},
	{"name": "나고야 그램퍼스", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Nagoya_Grampus.svg", "shortName": "N.그램퍼스"},
	{"name": "알비렉스 니가타", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Albirex_Niigata.svg", "shortName": "A.니가타"},
	{"name": "사간 도스", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Sagan_Tosu.svg", "shortName": "사간 도스"},
	{"name": "FC 도쿄", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/FC_Tokyo.svg", "shortName": "FC 도쿄"},
	{"name": "홋카이도 콘사돌레 삿포로", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Hokkaido_Consadole_Sapporo.svg", "shortName": "HC.삿포로"},
	{"name": "쇼난 벨마레", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Shonan_Bellmare.svg", "shortName": "쇼난 벨마레"},
	{"name": "감바 오사카", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Gamba_Osaka.svg", "shortName": "감바 오사카"},
	{"name": "세레소 오사카", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Cerezo_Osaka.svg", "shortName": "세레소 오사카"},
	{"name": "요코하마 FC", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Yokohama_FC.svg", "shortName": "요코하마 FC"},
	{"name": "요코하마 F. 마리노스", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Yokohama_F._Marinos.svg", "shortName": "Y.마리노스"},
	{"name": "우라와 레드 다이아몬즈", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Urawa_Red_Diamonds.svg", "shortName": "U.레드 다이아몬즈"},
	{"name": "아비스파 후쿠오카", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Avispa_Fukuoka.svg", "shortName": "A.후쿠오카"},
	{"name": "산브레체 히로시마", "logos": "https://indvel.github.io/utils/fsm/logos/J1League/Sanfrecce_Hiroshima.svg", "shortName": "S.히로시마"}
];

const EFL = [
	{"name": "노리치 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Norwich_City_FC.svg", "shortName": "노리치"},
	{"name": "레스터 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Leicester_City_FC.svg", "shortName": "레스터"},
	{"name": "로더럼 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Rotherham_United_FC.svg", "shortName": "로더럼"},
	{"name": "미들즈브러 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Middlesbrough_FC.svg", "shortName": "미들즈브러"},
	{"name": "밀월 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Millwall_FC.svg", "shortName": "밀월"},
	{"name": "버밍엄 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Birmingham_City_FC.svg", "shortName": "버밍엄"},
	{"name": "브리스톨 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Bristol_City_FC.svg", "shortName": "브리스톨"},
	{"name": "블랙번 로버스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Blackburn_Rovers_FC.svg", "shortName": "블랙번 로버스"},
	{"name": "사우스햄튼 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Southampton_FC.svg", "shortName": "사우스햄튼"},
	{"name": "셰필드 웬즈데이 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Sheffield_Wednesday_FC.svg", "shortName": "S.웬즈데이"},
	{"name": "스완지 시티 AFC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Swansea_City_FC.svg", "shortName": "스완지"},
	{"name": "스토크 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Stoke_City_FC.svg", "shortName": "스토크 시티"},
	{"name": "왓포드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Watford_FC.svg", "shortName": "왓포드"},
	{"name": "웨스트 브롬위치 알비온 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/West_Bromwich_Albion_FC.svg", "shortName": "웨스트 브롬위치"},
	{"name": "입스위치 타운 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Ipswich_Town_FC.svg", "shortName": "입스위치"},
	{"name": "카디프 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Cardiff_City_FC.svg", "shortName": "카디프 시티"},
	{"name": "코번트리 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Coventry_City_FC.svg", "shortName": "코번트리"},
	{"name": "퀸즈 파크 레인저스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Queens_Park_Rangers_FC.svg", "shortName": "QPR"},
	{"name": "프레스턴 노스 엔드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Preston_North_End_FC.svg", "shortName": "P.노스 엔드"},
	{"name": "플리머스 아가일 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Plymouth_Argyle_FC.svg", "shortName": "플리머스 아가일"},
	{"name": "허더즈필드 타운 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Huddersfield_Town_AFC.svg", "shortName": "허더즈필드"},
	{"name": "헐 시티 AFC", "logos": "https://indvel.github.io/utils/fsm/logos/EFL/Hull_City_AFC.svg", "shortName": "헐 시티"},
	{"name": "셰필드 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Sheffield_United_FC_logo.svg", "shortName": "셰필드"},
	{"name": "찰턴 애슬레틱 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Charlton_Athletic_FC.svg", "shortName": "찰턴 애슬레틱"},
	{"name": "더비 카운티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Derby_County_FC.svg", "shortName": "더비 카운티"},
	{"name": "옥스퍼드 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Oxford_United_FC.svg", "shortName": "옥스퍼드"},
	{"name": "포츠머스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Portsmouth_FC.svg", "shortName": "포츠머스"},
	{"name": "렉섬 AFC", "logos": "https://indvel.github.io/utils/fsm/logos/EPL/Wrexham_AFC.svg", "shortName": "렉섬"}
];

const Superliga = [
	{"name": "오르후스 GF", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Aarhus_GF.svg", "shortName": "오르후스"},
	{"name": "브뢴뷔 IF", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Brondby_IF.svg", "shortName": "브뢴뷔"},
	{"name": "FC 코펜하겐", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/FC_Kobenhavn.svg", "shortName": "코펜하겐"},
	{"name": "FC 미트윌란", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/FC_Midtjylland.svg", "shortName": "미트윌란"},
	{"name": "FC 노르셸란", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/FC_Nordsjaelland.svg", "shortName": "노르셸란"},
	{"name": "흐비도우레 IF", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Hvidovre_IF.svg", "shortName": "흐비도우레"},
	{"name": "릥뷔 BK", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Lyngby_BK.svg", "shortName": "릥뷔"},
	{"name": "오덴세 BK", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Odense_BK.svg", "shortName": "오덴세"},
	{"name": "라네르스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Randers_FC.svg", "shortName": "라네르스"},
	{"name": "실케보르 IF", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Silkeborg_IF.svg", "shortName": "실케보르"},
	{"name": "바일레 BK", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Vejle_BK.svg", "shortName": "바일레"},
	{"name": "비보르 FF", "logos": "https://indvel.github.io/utils/fsm/logos/Superliga/Viborg_FF.svg", "shortName": "비보르"}
];

const SuperLig = [
	{"name": "아다나 데미르스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Adana_Demirspor.svg", "shortName": "데미르스포르"},
	{"name": "알란야스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Alanyaspor.svg", "shortName": "알란야스포르"},
	{"name": "안탈리아스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Antalyaspor.svg", "shortName": "안탈리아스포르"},
	{"name": "베식타스 JK", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Besiltas_JK.svg", "shortName": "베식타스"},
	{"name": "차이쿠르 리제스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Caykur_Rizespor.svg", "shortName": "C.리제스포르"},
	{"name": "파티흐 카라귐뤼크 SK", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Fatih_Karagumruk_SK.svg", "shortName": "F.카라귐뤼크"},
	{"name": "페네르바흐체 SK", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Fenerbahce_SK.svg", "shortName": "페네르바흐체"},
	{"name": "갈라타사라이 SK", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Galatasaray_SK.svg", "shortName": "갈라타사라이"},
	{"name": "가지안테프 FK", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Gaziantep_FK.svg", "shortName": "가지안테프"},
	{"name": "하타이스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Hatayspor.svg", "shortName": "하타이스포르"},
	{"name": "이스탄불 바샥셰히르 FK", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/istanbul_Basakehir_FK.svg", "shortName": "I.바샥셰히르"},
	{"name": "이스탄불스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/istanbulspor.svg", "shortName": "이스탄불스포르"},
	{"name": "카슴파샤 SK", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Kasimpasa_SK.svg", "shortName": "카슴파샤"},
	{"name": "콘야스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Konyaspor.svg", "shortName": "콘야스포르"},
	{"name": "카이세리스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Kayserispor.svg", "shortName": "카이세리스포르"},
	{"name": "MKE 앙카라귀쥐", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/MKE_Ankaragucu.svg", "shortName": "MKE 앙카라귀쥐"},
	{"name": "펜디크스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Pendikspor.svg", "shortName": "펜디크스포르"},
	{"name": "삼순스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Samsunspor.svg", "shortName": "삼순스포르"},
	{"name": "시바스스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Sivasspor.svg", "shortName": "시바스스포르"},
	{"name": "트라브존스포르", "logos": "https://indvel.github.io/utils/fsm/logos/SuperLig/Trabzonspor.svg", "shortName": "트라브존스포르"}
];

const RSL = [
	{"name": "압하 FC", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Abha_FC.svg", "shortName": "압하"},
	{"name": "알 아흘리", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Ahli_SFC.svg", "shortName": "알 아흘리"},
	{"name": "알 파이하", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Fayha_FC.svg", "shortName": "알 파이하"},
	{"name": "알 힐랄", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Hilal_SFC.svg", "shortName": "알 힐랄"},
	{"name": "알 이티하드", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Ittihad.svg", "shortName": "알 이티하드"},
	{"name": "알 나스르", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Nassr_FC_New.svg", "shortName": "알 나스르"},
	{"name": "알 라에드", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Read_FC.webp", "shortName": "알 라에드"},
	{"name": "알 샤바브", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Shabab.svg", "shortName": "알 샤바브"},
	{"name": "알 타아원", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Taawoun_FC.svg", "shortName": "알 타아원"},
	{"name": "알 타이", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Tai_FC.svg", "shortName": "알 타이"},
	{"name": "알 웨흐다", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Wehda_FC.webp", "shortName": "알 웨흐다"},
	{"name": "알 하젬", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al-Hazem_SC.webp", "shortName": "알 하젬"},
	{"name": "알 오크두드 클럽", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Okhdood_Club_New.svg", "shortName": "알 오크두드"},
	{"name": "알 리야드", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al-Riyadh.webp", "shortName": "알 리야드"},
	{"name": "알 콜루드 클럽", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Al_Kholood_Club.svg", "shortName": "알 콜루드"},
	{"name": "다마크", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Damac_FC.svg", "shortName": "다마크"},
	{"name": "에티파크", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Ettifaq_FC.svg", "shortName": "에티파크"},
	{"name": "칼리즈", "logos": "https://indvel.github.io/utils/fsm/logos/RSL/Khaleej_FC.webp", "shortName": "칼리즈"}
];

const Eredivisie = [
	{"name": "알크마르 잔스트레이크", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/Alkmaar_Zaanstreek.svg", "shortName": "A.잔스트레이크"},
	{"name": "알메러 시티", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/Almere_City_FC.svg", "shortName": "알메러 시티"},
	{"name": "엑셀시오르 로테르담", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/Excelsior_Rotterdam.svg", "shortName": "E.로테르담"},
	{"name": "FC 트벤테", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/FC_Twente.svg", "shortName": "트벤테"},
	{"name": "FC 위트레흐트", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/FC_Utrecht.svg", "shortName": "위트레흐트"},
	{"name": "FC 폴렌담", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/FC_Volendam.svg", "shortName": "폴렌담"},
	{"name": "페예노르트 로테르담", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/Feyenoord_Rotterdam.svg", "shortName": "페예노르트"},
	{"name": "포르튀나 시타르트", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/Fortuna_Sittard.svg", "shortName": "포르튀나"},
	{"name": "고 어헤드 이글스", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/Go_Ahead_Eagles.svg", "shortName": "고 어헤드 이글스"},
	{"name": "헤라클레스 알멜로", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/Heracles_Almelo.svg", "shortName": "헤라클레스"},
	{"name": "NEC 네이메헌", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/NEC_Nijmegen.svg", "shortName": "네이메헌"},
	{"name": "PEC 즈볼러", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/PEC_Zwolle.svg", "shortName": "즈볼러"},
	{"name": "PSV 에인트호번", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/PSV_Eindhoven.svg", "shortName": "PSV"},
	{"name": "RKC 발베이크", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/RKC_Waalwijk.svg", "shortName": "발베이크"},
	{"name": "SBV 피테서", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/SBV_Vitesse.svg", "shortName": "피테서"},
	{"name": "SC 헤이렌베인", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/SC_Heerenveen.svg", "shortName": "헤이렌베인"},
	{"name": "스파르타 로테르담", "logos": "https://indvel.github.io/utils/fsm/logos/Eredivisie/Sparta_Rotterdam.svg", "shortName": "스파르타 로테르담"}
];

const MLS = [
	{"name": "애틀랜타 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/AtlantaUnitedFC.svg", "shortName": "애틀랜타"},
	{"name": "오스틴 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/AustinFC.svg", "shortName": "오스틴"},
	{"name": "CF 몽레알", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/CFMontreal.svg", "shortName": "몽레알"},
	{"name": "샬럿 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/CharlotteFC.svg", "shortName": "샬럿"},
	{"name": "시카고 파이어 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/ChicagoFireFC.svg", "shortName": "시카고"},
	{"name": "콜로라도 래피즈", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/ColoradoRapids.svg", "shortName": "콜로라도"},
	{"name": "콜럼버스 크루", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/ColumbusCrew.svg", "shortName": "콜럼버스"},
	{"name": "DC 유나이티드", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/DCUnited.svg", "shortName": "DC 유나이티드"},
	{"name": "FC 신시내티", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/FCCincinnati.svg", "shortName": "신시내티"},
	{"name": "FC 댈러스", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/FCDallas.svg", "shortName": "댈러스"},
	{"name": "휴스턴 다이너모 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/HoustonDynamoFC.svg", "shortName": "휴스턴"},
	{"name": "인터 마이애미 CF", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/InterMiamiCF.svg", "shortName": "인터 마이애미"},
	{"name": "LA FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/LAFC.svg", "shortName": "LA FC"},
	{"name": "LA 갤럭시", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/LAGalaxy.svg", "shortName": "LA 갤럭시"},
	{"name": "미네소타 유나이티드 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/MinnesotaUnitedFC.svg", "shortName": "미네소타"},
	{"name": "내슈빌 SC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/NashvilleSC.svg", "shortName": "내슈빌"},
	{"name": "뉴 잉글랜드 레볼루션 ", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/NewEnglandRevolution.svg", "shortName": "뉴 잉글랜드"},
	{"name": "뉴욕 시티 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/NewYorkCityFC.svg", "shortName": "뉴욕 시티"},
	{"name": "뉴욕 레드불스", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/NewYorkRedBulls.svg", "shortName": "뉴욕 레드불스"},
	{"name": "올랜도 시티 SC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/OrlandoCitySC.svg", "shortName": "올랜도 시티"},
	{"name": "필라델피아 유니온", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/PhiladelphiaUnion.svg", "shortName": "필라델피아"},
	{"name": "포틀랜드 팀버스", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/PortlandTimbers.svg", "shortName": "포틀랜드"},
	{"name": "레알 솔트레이크", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/RealSaltLake.svg", "shortName": "레알 솔트레이크"},
	{"name": "샌디에이고 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/SanDiegoFC.svg", "shortName": "샌디에이고"},
	{"name": "산호세 어스퀘이크스", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/SanJoseEarthquakes.svg", "shortName": "산호세"},
	{"name": "시애틀 사운더스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/SeattleSoundersFC.svg", "shortName": "시애틀"},
	{"name": "스포팅 캔자스시티", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/SportingKansasCity.svg", "shortName": "캔자스시티"},
	{"name": "세인트루이스 시티 SC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/StLouisCitySC.svg", "shortName": "세인트루이스"},
	{"name": "토론토 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/TorontoFC.svg", "shortName": "토론토"},
	{"name": "밴쿠버 화이트캡스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/MLS/VancouverWhitecapsFC.svg", "shortName": "밴쿠버"}
];

const PrimeiraLiga = [
	{"name": "AVS 푸트볼 SAD", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/AVSfutebolSAD.svg", "shortName": "AVS 푸트볼"},
	{"name": "보아비스타 FC", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/BoavistaFC.svg", "shortName": "보아비스타"},
	{"name": "카사 피아 AC", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/CasaPiaAC.svg", "shortName": "카사 피아"},
	{"name": "CD 나시오날", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/CDNacional.svg", "shortName": "나시오날"},
	{"name": "CD 산타 클라라", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/CDSantaClara.svg", "shortName": "산타 클라라"},
	{"name": "CF 이스트렐라 다 아마도라", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/CFEstreladaAmadora.svg", "shortName": "이스트렐라"},
	{"name": "FC 아로카", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/FCArouca.svg", "shortName": "FC 아로카"},
	{"name": "FC 파말리캉", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/FCFamalicao.svg", "shortName": "FC 파말리캉"},
	{"name": "FC 포르투", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/FCPorto.svg", "shortName": "FC 포르투"},
	{"name": "GD 이스토릴 프라이아", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/GDEstorilPraia.svg", "shortName": "GD 이스토릴"},
	{"name": "질 비센트 FC", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/GilVicenteFC.svg", "shortName": "질 비센트"},
	{"name": "모레이렌스 FC", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/MoreirenseFC.svg", "shortName": "모레이렌스"},
	{"name": "히우 아브 FC", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/RioAveFC.svg", "shortName": "히우 아브"},
	{"name": "SC 브라가", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/SCBraga.svg", "shortName": "SC 브라가"},
	{"name": "SC 파렌스", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/SCFarense.svg", "shortName": "SC 파렌스"},
	{"name": "SL 벤피카", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/SLBenfica.svg", "shortName": "SL 벤피카"},
	{"name": "스포르팅 CP", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/SportingCP.svg", "shortName": "스포르팅 CP"},
	{"name": "비토리아 SC", "logos": "https://indvel.github.io/utils/fsm/logos/PrimeiraLiga/VitoriaSC.svg", "shortName": "비토리아 SC"}
];

const Eliteserien = [
	{"name": "브뤼네 FK", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Bryne_FK.svg", "shortName": "브뤼네"},
	{"name": "보되/글림트", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/FK_Bodo_Glimt.svg", "shortName": "보되/글림트"},
	{"name": "FK 하우게순", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/FK_Haugesund.svg", "shortName": "하우게순"},
	{"name": "프레드릭스타 FK", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Fredrikstad_FK.svg", "shortName": "프레드릭스타"},
	{"name": "하마르카메라테네", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Hamarkameratene.svg", "shortName": "하마르카메라테네"},
	{"name": "KFUM-카메라테네 오슬로", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/KFUM_Kameratene_Oslo.svg", "shortName": "KFUM"},
	{"name": "크리스티안순 BK", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Kristiansund_BK.svg", "shortName": "크리스티안순"},
	{"name": "몰데 FK", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Molde_FK.svg", "shortName": "몰데"},
	{"name": "로센보르그 BK", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Rosenborg_BK.svg", "shortName": "로센보르그"},
	{"name": "사네피오르 포트발", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Sandefjord_Fotball.svg", "shortName": "사네피오르"},
	{"name": "사르프스보르그 08 FF", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Sarpsborg_08_FF.svg", "shortName": "사르프스보르그"},
	{"name": "SK 브란", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/SK_Brann.svg", "shortName": "SK 브란"},
	{"name": "스트룀스고세 IF", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Stromsgodset_Toppfotball.svg", "shortName": "스트룀스고세"},
	{"name": "트롬쇠 IL", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Tromso_IL.svg", "shortName": "트롬쇠"},
	{"name": "볼레렝아 포트발", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Valerenga_Fotball.svg", "shortName": "볼레렝아"},
	{"name": "비킹 FK", "logos": "https://indvel.github.io/utils/fsm/logos/Eliteserien/Viking_FK.svg", "shortName": "비킹"}
];

const ChanceLiga = [
	{"name": "FK 두클라 프라하", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FK_Dukla_Praha.svg", "shortName": "두클라"},
	{"name": "FK 믈라다볼레슬라프", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FK_Mlada_Boleslav.svg", "shortName": "믈라다볼레슬라프"},
	{"name": "FC 바니크 오스트라바", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FC_Banik_Ostrava.svg", "shortName": "오스트라바"},
	{"name": "보헤미안스 프라하 1905", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/Bohemians_1905.svg", "shortName": "보헤미안스"},
	{"name": "FC 빅토리아 플젠", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FC_Viktoria_Plzen.svg", "shortName": "빅토리아"},
	{"name": "AC 스파르타 프라하", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/AC_Sparta_Praha.svg", "shortName": "스파르타"},
	{"name": "SK 슬라비아 프라하", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/SK_Slavia_Praha.svg", "shortName": "슬라비아"},
	{"name": "1. FC 슬로바츠코", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/1._FC_Slovacko.svg", "shortName": "슬로바츠코"},
	{"name": "FC 슬로반 리베레츠", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FC_Slovan_Libersec.svg", "shortName": "리베레츠"},
	{"name": "SK 시그마 올로모우츠", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/SK_Sigma_Olomouc.svg", "shortName": "올로모우츠"},
	{"name": "FK 야블로네츠", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FK_Jablonec.svg", "shortName": "야블로네츠"},
	{"name": "FC 즐린", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FC_Zlin.svg", "shortName": "즐린"},
	{"name": "MFK 카르비나", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/MFK_Karvina.svg", "shortName": "카르비나"},
	{"name": "FK 테플리체", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FK_Teplice.svg", "shortName": "테플리체"},
	{"name": "FK 파르두비체", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FK_Pardubice.svg", "shortName": "파르두비체"},
	{"name": "FC 흐라데츠크랄로베", "logos": "https://indvel.github.io/utils/fsm/logos/ChanceLiga/FC_Hradec_Kralove.svg", "shortName": "흐라데츠크랄로베"}
]
